// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ClassCreation 
// ==================================================================
   [Indication, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_ClassCreation notifies when a new class is defined in the schema."
        )]
class CIM_ClassCreation : CIM_ClassIndication {


};
