// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ClassDeletion 
// ==================================================================
   [Indication, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_ClassDeletion notifies when a class is deleted from the schema."
        )]
class CIM_ClassDeletion : CIM_ClassIndication {


};
