// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ClassModification 
// ==================================================================
   [Indication, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_ClassModification notifies when a class definition in the "
       "schema is modified." )]
class CIM_ClassModification : CIM_ClassIndication {

      [Required, Description ( 
          "A copy of the \'previous\' class definition whose change "
          "generated the Indication. PreviousClassDefinition "
          "contains an \'older\' copy of the class\' information, "
          "as compared to what is found in the ClassDefinition "
          "property (inherited from ClassIndication)." ), 
       EmbeddedObject]
   string PreviousClassDefinition;


};
