// Copyright (c) 2005-2006 DMTF.  All rights reserved.
// <change cr="WIPCR00330.003" type="add">  	
// CIM_ListenerDestination changes.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ListenerDestinationCIMXML 
// ==================================================================
   [Version ( "2.14.0" ), 
    UMLPackagePath ( "CIM::Event" ), 
    Description ( 
       "CIM_ListenerDestinationCIMXML describes the destination for "
       "CIM Export Messages to be delivered via CIM-XML." )]
class CIM_ListenerDestinationCIMXML : CIM_ListenerDestination {

      [Required, Override ( "Destination" ), 
       Description ( 
          "The destination URL to which CIM-XML Export Messages are "
          "to be delivered.The scheme prefix MUST be consistent "
          "with the DMTF CIM-XML specifications.If a scheme prefix "
          "is not specified, the scheme \"http:\" MUST be assumed." )]
   string Destination;


};
