//Copyright (c) 2007 DMTF. All Rights Reserved.
   [Experimental, Version ( "2.17.0" ), 
    UMLPackagePath ( "CIM::Physical::Package" ), 
    Description ( 
       "The ComponentBay class represents a location within a "
       "PhysicalPackagedesigned to hold or contain other "
       "PhysicalPackages of a particular type or design into which "
       "these other PhysicalPackages may be inserted. This is distinct "
       "from a PhysicalConnector and its child class(es) where the "
       "focus of the model is the mechanism through which the "
       "PhysicalPackages are joined." )]
class CIM_ComponentBay : CIM_PhysicalElement {

      [Description ( 
          "Identifier provides identifying information about the "
          "bay. For example, it may correspond to the number silk "
          "screened on the container physical package." )]
   string Identifier;

      [Description ( 
          "An array of strings that identify the components that "
          "are compatible and can be inserted in a bay. This allows "
          "vendors to provide clues to the system administrators by "
          "providing sufficient information to request the "
          "appropriate hardware that can populate the bay. In order "
          "to ensure uniqueness each value defined by the vendor "
          "for use in the VendorCompatibilityStrings property shall "
          "be constructed using the following \'preferred\' "
          "algorithm: \n"
          ": \n"
          "Where and are separated by a colon \':\', and where "
          "shall include a copyrighted, trademarked or otherwise "
          "unique name that is owned by the business entity "
          "creating/defining the value, or is a registered ID that "
          "is assigned to the business entity by a recognized "
          "global authority (This is similar to the _ structure of "
          "Schema class names.) In addition, to ensure uniqueness "
          "shall not contain a colon (\':\'). When using this "
          "algorithm, the first colon to appear in InstanceID shall "
          "appear between and . is chosen by the business entity "
          "and should not be re-used to identify different "
          "underlying (real-world) elements." ), 
       ModelCorrespondence { 
          "CIM_PhysicalPackage.VendorCompatibilityStrings" }]
   string VendorCompatibilityStrings[];


};
