// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ParticipatesInSet
// ==================================================================
   [Association, Deprecated { "CIM_MemberOfCollection" }, 
    Experimental, Aggregation, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Physical::Misc" ), 
    Description ( 
       "ParticipatesInSet indicates which PhysicalElements are "
       "replaced together. Since ReplacementSet was updated to "
       "subclass from CIM_Collection, this separate association of "
       "members into the set is no longer needed. It is deprecated in "
       "lieu of MemberOfCollection." )]
class CIM_ParticipatesInSet {

      [Deprecated { "CIM_MemberOfCollection.Collection" }, 
       Key, Aggregate, Description ( "The ReplacementSet." )]
   CIM_ReplacementSet REF Set;

      [Deprecated { "CIM_MemberOfCollection.Member" }, 
       Key, Description ( 
          "The PhysicalElement which should be replaced with other "
          "Elements, as a Set." )]
   CIM_PhysicalElement REF Element;


};
