// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AuthorizationRuleAppliesToIdentity 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "AuthorizationRuleAppliesToRole makes explicit that an "
       "AuthorizationRule is CURRENTLY applied to a particular "
       "Identity that is to be considered an authorized subject." )]
class CIM_AuthorizationRuleAppliesToIdentity : CIM_PolicySetAppliesToElement {

      [Key, Override ( "PolicySet" ), 
       Description ( 
          "The AuthenticationRule that is currently applied to this Identity."
           )]
   CIM_AuthorizationRule REF PolicySet;

      [Key, Override ( "ManagedElement" ), 
       Description ( 
          "An Identity to which this AuthorizationRule applies." )]
   CIM_Identity REF ManagedElement;


};
