// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AuthorizationRuleAppliesToPrivilege 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Policy" ), 
    Description ( 
       "AuthorizationRuleAppliesToRole makes explicit that an "
       "AuthorizationRule is CURRENTLY applied to a particular "
       "Privilege." )]
class CIM_AuthorizationRuleAppliesToPrivilege : CIM_PolicySetAppliesToElement {

      [Key, Override ( "PolicySet" ), 
       Description ( 
          "The AuthenticationRule that is currently applied to this "
          "Privilege." )]
   CIM_AuthorizationRule REF PolicySet;

      [Key, Override ( "ManagedElement" ), 
       Description ( 
          "An Privilege to which this AuthorizationRule applies." )]
   CIM_Privilege REF ManagedElement;


};
