// Copyright (c) 2008 DMTF.  All rights reserved.
   [Experimental, Abstract, Version ( "2.19.0" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "A Share is representative of an object presented for use (or "
       "shared) across systems. Instances of CIM_Share are associated "
       "with the shared object on the \'server\'-side via the "
       "CIM_SharedElement association. Shares are mounted on the "
       "\'client\'-side (usually into another namespace) via the "
       "CIM_Import Share association. CIM_Share is Abstract to force "
       "subclassing to define the semantics of sharing." )]
class CIM_Share : CIM_EnabledLogicalElement {

      [Key, Override ( "InstanceID" ), 
       Description ( 
          "Within the scope of the instantiating Namespace, "
          "InstanceID opaquely and uniquely identifies an instance "
          "of this class. In order to ensure uniqueness within the "
          "NameSpace, the value of InstanceID SHOULD be constructed "
          "using the following \'preferred\' algorithm: \n"
          "<OrgID>:<LocalID> \n"
          "Where <OrgID> and <LocalID> are separated by a colon "
          "\':\', and where <OrgID> MUST include a copyrighted, "
          "trademarked or otherwise unique name that is owned by "
          "the business entity creating/defining the InstanceID, or "
          "is a registered ID that is assigned to the business "
          "entity by a recognized global authority. (This is "
          "similar to the <Schema Name>_<Class Name> structure of "
          "Schema class names.) In addition, to ensure uniqueness "
          "<OrgID> MUST NOT contain a colon (\':\'). When using "
          "this algorithm, the first colon to appear in InstanceID "
          "MUST appear between <OrgID> and <LocalID>. \n"
          "\n"
          "<LocalID> is chosen by the business entity and SHOULD "
          "not be re-used to identify different underlying "
          "(real-world) elements. If the above \'preferred\' "
          "algorithm is not used, the defining entity MUST assure "
          "that the resultant InstanceID is not re-used across any "
          "InstanceIDs produced by this or other providers for this "
          "instance\'s NameSpace." )]
   string InstanceID;


};
