// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_HostingCS
// ==================================================================
   [Association, Deprecated { "CIM_HostedDependency" }, 
    Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::SystemElements" ), 
    Description ( 
       "A VirtualComputerSystem is hosted on another ComputerSystem. "
       "This association makes that relationship explicit. \n"
       "The usage of this class is being deprecated in lieu of using "
       "the HostedDependency association between ComputerSystems." )]
class CIM_HostingCS : CIM_HostedDependency {

      [Deprecated { "CIM_HostedDependency.Antecedent" }, 
       Override ( "Antecedent" ), 
       Min ( 1 ), 
       Description ( "The hosting ComputerSystem." )]
   CIM_ComputerSystem REF Antecedent;

      [Deprecated { "CIM_HostedDependency.Dependent" }, 
       Override ( "Dependent" ), 
       Description ( "The VirtualComputerSystem." )]
   CIM_VirtualComputerSystem REF Dependent;


};
