// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NFSShare 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "An NFSShare represents a Directory associated via "
       "CIM_SharedElement that is made accessible to other systems. On "
       "the client-side, the NFSShare is associated with its mount "
       "point via CIM_ImportedShare." )]
class CIM_NFSShare : CIM_FileShare {

      [Override ( "Name" ), 
       Description ( 
          "The Name property, inherited from Share, defines the "
          "shared name by which the shared object is exported. For "
          "NFS, this will typically be the pathname of the exported "
          "directory, using forward slashes \'/\' to precede "
          "directory names in the path." )]
   string Name;


};
