// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SystemPartition
// ==================================================================
   [Association, Deprecated { "CIM_HostedDependency" }, 
    Experimental, Aggregation, Composition, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::SystemElements" ), 
    Description ( 
       "A Partition is an instance of a UnitaryComputerSystem (with "
       "its own OperatingSystem and Devices dedicated to the "
       "Partition) that is supported by underlying hardware and "
       "software. A Partition is not a virtualization of a Computer "
       "System, but the segmentation of the System\'s compute "
       "capabilities. Partitions can run independent copies of "
       "possibly different OperatingSystems and have dedicated "
       "Devices. The \'real\', underlying System (perhaps a Cluster or "
       "another UnitaryComputerSystem) aggregates its Partitions. "
       "These semantics are described by the System Partition "
       "association. \n"
       "The use of this association has been deprecated in lieu of "
       "using HostedDependency." )]
class CIM_SystemPartition : CIM_ComponentCS {

      [Deprecated { "CIM_HostedDependency.Antecedent" }, 
       Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( 
          "The \'underlying\' ComputerSystem that hosts a Partition." )]
   CIM_ComputerSystem REF GroupComponent;

      [Deprecated { "CIM_HostedDependency.Antecedent" }, 
       Override ( "PartComponent" ), 
       Description ( "The System Partition." )]
   CIM_UnitaryComputerSystem REF PartComponent;


};
