// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ImportedShare 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "An association derived from MountedElement for attaching an "
       "imported FileShare to a LogicalFile (or Directory). The "
       "semantics of this relationship require that the SameElement be "
       "an imported FileShare." )]
class CIM_ImportedShare : CIM_MountedElement {

      [Override ( "SystemElement" ), 
       Description ( 
          "The LogicalFile that the SameElement (a FileShare) will "
          "be attached to and that will provide access to the "
          "SameElement." )]
   CIM_LogicalElement REF SystemElement;

      [Override ( "SameElement" ), 
       Max ( 1 ), 
       Description ( 
          "The FileShare that is being made available using the "
          "SystemElement (a LogicalFile) as a surrogate." )]
   CIM_LogicalElement REF SameElement;


};
