// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_BatchSAP 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "The ServiceAccessPoint for accessing a BatchService. The "
       "relationship between the AccessPoint and the Service is "
       "described by instantiating the ServiceAccessBySAP association." )]
class CIM_BatchSAP : CIM_ServiceAccessPoint {

      [Description ( 
          "Specifies the batch submission procotols that this "
          "AccessPoint uses. Note that each entry of this array is "
          "related to the corresponding entry in the "
          "BatchProtocolInfo array that is located at the same "
          "index." ), 
       ValueMap { "0", "1", "2" }, 
       Values { "Unknown", "Other", "Local" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_BatchSAP.BatchProtocolInfo" }]
   uint16 BatchProtocol[];

      [Description ( 
          "Provides clarifying or additional information about the "
          "protocols supported by this AccessPoint. Note, each "
          "entry of this array is related to the corresponding "
          "entry in the BatchProtocol array that is located at the "
          "same index." ), 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { "CIM_BatchSAP.BatchProtocol" }]
   string BatchProtocolInfo[];


};
