// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ExecutionTarget 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "ExecutionTarget represents the association between a System "
       "and a Job, describing that the System is running the job." )]
class CIM_ExecutionTarget : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The System that is running the Job." )]
   CIM_System REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Job that is run." )]
   CIM_Job REF Dependent;


};
