// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RecoveryJob 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "CIM_RecoveryJob specifies the Job that should be run to clean "
       "up or recover from the unsuccessful completion of the "
       "Dependent Job." )]
class CIM_RecoveryJob : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "Antecedent represents the recovery Job." )]
   CIM_Job REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "Dependent represents the Job which may not successfully "
          "complete and which is dependent on the \'RecoveryJob\' "
          "for cleanup." )]
   CIM_Job REF Dependent;


};
