// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00797.003" type = "Add"> Change Diagnostic Settings 
// to derive from CIM_SettingData rather than CIM_Setting.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_CorrespondingSettingDataRecord
// ==================================================================
   [Association, Experimental, Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::System::Diagnostics" ), 
    Description ( 
       "CorrespondingSettingDataRecord is used to tie a log record to "
       "its corresponding setting data record." )]
class CIM_CorrespondingSettingDataRecord {

      [Key, Description ( "The record containing the result data." )]
   CIM_DiagnosticRecord REF DataRecord;

      [Key, Description ( 
          "The record containing the DiagnosticSettingData that "
          "were used when the result was created." )]
   CIM_DiagnosticSettingDataRecord REF SettingsRecord;


};
