//Copyright (c) 2007 DMTF. All Rights Reserved.
   [Experimental, Version ( "2.17.0" ), 
    UMLPackagePath ( "CIM::System::Virtualization" ), 
    Description ( 
       "Capabilities of a CIM_VirtualSystemMigrationService." )]
class CIM_VirtualSystemMigrationCapabilities : CIM_Capabilities {

      [Description ( 
          "Enumeration of method identifiers whose implementation "
          "may be synchronous; that is, the operation may complete "
          "immediately and therefore the method may not return a "
          "job." ), 
       ValueMap { "2", "3", "4", "5", ".." }, 
       Values { "MigrateVirtualSystemToHostSupported", 
          "MigrateVirtualSystemToSystemSupported", 
          "CheckVirtualSystemIsMigratableToHostSupported", 
          "CheckVirtualSystemIsMigratableToSystemSupported", 
          "DMTF Reserved" }]
   uint16 SynchronousMethodsSupported[];

      [Description ( 
          "Enumeration of method identifiers whose implementation "
          "may be asynchronous; that is, the operation may not "
          "complete immediately and instead the method may return a "
          "job." ), 
       ValueMap { "2", "3", ".." }, 
       Values { "MigrateVirtualSystemToHostSupported", 
          "MigrateVirtualSystemToSystemSupported", "DMTF Reserved" }]
   uint16 AsynchronousMethodsSupported[];

      [Description ( 
          "Array of format designators. Values indicate that the "
          "designated format is supported for input values of the "
          "DestinationHost parameter of the "
          "MigrateVirtualSystemToHost( ) method or the "
          "CheckVirtualSystemIsMigratableToHost( ) method of the "
          "associated instance of the "
          "CIM_VirtualSystemMigrationService class.\n"
          "Format designators designate the following formats:\n"
          "2 - Support of the Domain Name text format according to "
          "RFC 1035\n"
          "3 - Support of the IPv4 dotted decimal format according "
          "to RFC 1208\n"
          "4 - Support of the IPv6 text format according to RFC "
          "4291" ), 
       ValueMap { "2", "3", "4", ".." }, 
       Values { "DomainNameFormatSupported", 
          "IPv4DottedDecimalFormatSupported", 
          "IPv6TextFormatSupported", "DMTF Reserved" }, 
       ModelCorrespondence { 
          "CIM_VirtualSystemMigrationService.MigrateVirtualSystemToHost(DestinationHost)", 
          "CIM_VirtualSystemMigrationService.CheckVirtualSystemIsMigratableToHost(DestinationHost)" }]
   uint16 DestinationHostFormatsSupported[];


};
