// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_QueueForBatchService 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "This association indicates that a BatchService utilizes a "
       "particular JobQueue, to hold jobs submitted to the Service. At "
       "any point in time, the JobQueue can be full or otherwise not "
       "accepting jobs from the BatchService. This situation is "
       "indicated by the QueueAcceptingFromService Boolean property in "
       "this association." )]
class CIM_QueueForBatchService : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The BatchQueue that the Service utilizes." )]
   CIM_JobQueue REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The BatchService that puts BatchJobs on the Queue." )]
   CIM_BatchService REF Dependent;

      [Description ( 
          "Indicates that the BatchService can place jobs on the Queue."
           )]
   boolean QueueAcceptingFromService;


};
