// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SharedElement 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "SharedElement associates the Share to a LogicalElement that is "
       "being exported." )]
class CIM_SharedElement : CIM_LogicalIdentity {

      [Override ( "SystemElement" ), 
       Max ( 1 ), 
       Description ( 
          "The LogicalElement (or derived subclass) that is "
          "exported as a Share. In the context of file sharing, the "
          "LogicalElement will be a LogicalFile (or Directory "
          "derived from LogicalFile)." )]
   CIM_LogicalElement REF SystemElement;

      [Override ( "SameElement" ), 
       Description ( 
          "The Share that exposes the LogicalElement as an exported "
          "object. In the context of file sharing, the Share will "
          "be a FileShare (or a derived class)." )]
   CIM_Share REF SameElement;


};
