// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ImportedShareRoot 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "ImportedShareRoot provides additional information for the "
       "ImportedShare association. It requires that the Dependent be a "
       "FileShare and that the Antecedent be a LogicalFile." )]
class CIM_ImportedShareRoot : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The Directory that is the container for the "
          "LogicalElement that has a FileShare attached to it with "
          "ImportedShare." ), 
       ModelCorrespondence { "CIM_ImportedShare.SystemElement" }]
   CIM_LogicalElement REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( 
          "The FileShare that is attached to a Directory with ImportedShare."
           ), 
       ModelCorrespondence { "CIM_ImportedShare.SameElement" }]
   CIM_LogicalElement REF Dependent;


};
