// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DefaultElementCapabilities 
// ==================================================================
   [Association, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FilesystemServices" ), 
    Description ( 
       "An association between a CIM_ManagedElement and a "
       "CIM_Capabilities element that specifies that the managed "
       "element uses the other as a default. The CIM_Capabilities "
       "element MUST be associated to the CIM_ManagedElement by "
       "CIM_ElementCapabilities as well." )]
class CIM_DefaultElementCapabilities {

      [Key, Description ( 
          "The CIM_ManagedElement for which this Capabilities "
          "element is a default." )]
   CIM_ManagedElement REF ManagedElement;

      [Key, Max ( 1 ), 
       Description ( 
          "The CIM_Capabilities that is the default Capabilities "
          "element for the associated CIM_ManagedElement." )]
   CIM_Capabilities REF Capabilities;


};
