// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_NFS 
// ==================================================================
   [Deprecated { "CIM_FileShare" }, 
    Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "A class derived from RemoteFileSystem representing that the "
       "FileSystem is mounted, using the NFS protocol, from a "
       "ComputerSystem. The properties of the NFS object deal with the "
       "operational aspects of the mount and represent the client-side "
       "configuration for NFS access. The FileSystemType (inherited "
       "from FileSystem) should be set to indicate the type of this "
       "FileSystem as it appears to the client. \n"
       "This has been deprecated by CIM_FileShare, which works with "
       "the hosted service model. The HostedShare association will "
       "specify how the remote entity is imported and the "
       "ImportedFileShareSetting class provides the resources needed "
       "for the share to function. The properties of "
       "ImportedFileShareSetting deprecate specific properties of this "
       "class. All properties except \"Interrupt\" have been "
       "deprecated - it is not clear what or how this property should "
       "be deprecated." )]
class CIM_NFS : CIM_RemoteFileSystem {

      [Deprecated { 
          "CIM_ImportedFileShareSetting.ImportFailurePolicy" }, 
       Description ( 
          "If set to true: Once the FileSystem is mounted, NFS "
          "requests are retried until the hosting System responds. \n"
          "If set to false: Once the FileSystem is mounted, an "
          "error is returned if the hosting System does not "
          "respond." )]
   boolean HardMount;

      [Deprecated { "CIM_ImportedFileShareSetting.RequestRetryPolicy" }, 
       Description ( 
          "If set to true: Retries are performed in the foreground. \n"
          "If set to false: If the first mount attempt fails, "
          "retries are performed in the background." )]
   boolean ForegroundMount;

      [Deprecated { "No value" }, 
       Description ( 
          "If set to true: Interrupts are permitted for hard "
          "mounts. \n"
          "If set to false: Interrupts are ignored for hard mounts." )]
   boolean Interrupt;

      [Deprecated { "CIM_ImportedFileShareSetting.ImportRetriesMax" }, 
       Description ( 
          "Maximum number of mount failure retries allowed." )]
   uint16 MountFailureRetries;

      [Deprecated { 
          "CIM_ImportedFileShareSetting.TransmissionRetriesMax" }, 
       Description ( 
          "Maximum number of NFS retransmissions allowed." )]
   uint16 RetransmissionAttempts;

      [Deprecated { 
          "CIM_ImportedFileShareSetting.RetransmissionTimeoutMin" }, 
       Description ( "NFS timeout in tenths of a second." ), 
       Units ( "Tenths of Seconds" ), 
       PUnit ( "second * 10^-1" )]
   uint32 RetransmissionTimeout;

      [Deprecated { "CIM_ImportedFileShareSetting.ReadBufferSizeMin" }, 
       Description ( "Read buffer size in bytes." ), 
       Units ( "Bytes" ), 
       PUnit ( "byte" )]
   uint64 ReadBufferSize;

      [Deprecated { "CIM_ImportedFileShareSetting.WriteBufferSizeMin" }, 
       Description ( "Write buffer size in bytes." ), 
       Units ( "Bytes" ), 
       PUnit ( "byte" )]
   uint64 WriteBufferSize;

      [Deprecated { "CIM_ImportedFileShareSetting.AccessPoints" }, 
       Description ( 
          "The remote ComputerSystem\'s (ie, the NFS File "
          "\'Server\'s) UDP port number." )]
   uint32 ServerCommunicationPort;

      [Deprecated { 
          "CIM_ImportedFileShareSetting.AttributeCachingObjects" }, 
       Description ( 
          "If set to true: Control attribute caching is enabled. \n"
          "If set to false: Control attribute caching is disabled." )]
   boolean AttributeCaching;

      [Deprecated { 
          "CIM_ImportedFileShareSetting.AttributeCachingTimeMin" }, 
       Description ( 
          "Minimum number of seconds that cached attributes are "
          "held after file modification." ), 
       Units ( "Seconds" ), 
       PUnit ( "second" )]
   uint16 AttributeCachingForRegularFilesMin;

      [Deprecated { 
          "CIM_ImportedFileShareSetting.AttributeCachingTimeMax" }, 
       Description ( 
          "Maximum number of seconds that cached attributes are "
          "held after file modification." ), 
       Units ( "Seconds" ), 
       PUnit ( "second" )]
   uint16 AttributeCachingForRegularFilesMax;

      [Deprecated { 
          "CIM_ImportedFileShareSetting.AttributeCachingTimeMin" }, 
       Description ( 
          "Minimum number of seconds that cached attributes are "
          "held after directory update." ), 
       Units ( "Seconds" ), 
       PUnit ( "second" )]
   uint16 AttributeCachingForDirectoriesMin;

      [Deprecated { 
          "CIM_ImportedFileShareSetting.AttributeCachingTimeMax" }, 
       Description ( 
          "Maximum number of seconds that cached attributes are "
          "held after directory update." ), 
       Units ( "Seconds" ), 
       PUnit ( "second" )]
   uint16 AttributeCachingForDirectoriesMax;


};
