// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00792.001" type ="new">Replaces DiagnosticsLog
// class.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DiagnosticLog
// ==================================================================
   [Experimental, Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::System::Logs" ), 
    Description ( 
       "DiagnosticLog serves as an aggregation point for "
       "DiagnosticRecord objects. This class exists in order to "
       "encourage the use of a consolidated record management "
       "methodology for diagnostics. A common set of providers for "
       "this log and its associated records SHOULD be used to control "
       "functions such as record persistence, query support and "
       "overall data integrity in a consistent manner." )]
class CIM_DiagnosticLog : CIM_RecordLog {


};
