// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RemoteFileSystem
// ==================================================================
   [Deprecated { "CIM_FileShare" }, 
    Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "A class derived from FileSystem that represents access of the "
       "FileSystem via a network-related service. In this case, the "
       "file store is hosted by a computer, acting as a file server. "
       "For example, the file store for an NFS FileSystem is typically "
       "NOT on a ComputerSystem\'s locally controlled media, nor is it "
       "directly accessed through a device driver. Subclasses of "
       "RemoteFileSystem contain client-side configuration information "
       "related to the access of the FileSystem. \n"
       "This has been deprecated by CIM_FileShare, which works with "
       "the hosted service model. The HostedShare association will "
       "specify how the remote entity is imported and the "
       "ImportedFileShareSetting class provides the resources needed "
       "for the share to function." )]
class CIM_RemoteFileSystem : CIM_FileSystem {


};
