// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AttachedElement 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "An association between two LogicalElements indicating that the "
       "SameElement is being attached to the SystemElement." )]
class CIM_AttachedElement : CIM_LogicalIdentity {

      [Override ( "SystemElement" ), 
       Description ( 
          "The LogicalElement that the SameElement will be attached "
          "to and will provide access to the SameElement." )]
   CIM_LogicalElement REF SystemElement;

      [Override ( "SameElement" ), 
       Max ( 1 ), 
       Description ( 
          "The LogicalElement that is being made available using "
          "the SystemElement as a surrogate." )]
   CIM_LogicalElement REF SameElement;


};
