// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_CIFSShare 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "A CIFSShare represents a File, Directory, or Print Queue that "
       "is made accessible to other systems. If a File or Directory, "
       "it is associated via CIM_SharedElement. And on the "
       "client-side, the CIFSShare representing the File or Directory "
       "is associated with its mount point via CIM_ImportedShare. "
       "Other subclasses of LogicalIdentity would make the "
       "associations for other types of CIFSShare." )]
class CIM_CIFSShare : CIM_FileShare {

      [Override ( "Name" ), 
       Description ( 
          "The Name property, inherited from Share, defines the "
          "shared name by which the shared object is exported. For "
          "CIFS, this will typically be a single-level, "
          "user-friendly, system-unique name." )]
   string Name;


};
