// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ExecutionRequirement 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "ExecutionRequirement represents the restriction of a job to a "
       "specific set of nodes, processors, etc. that are aggregated "
       "into a ConcreteCollection." )]
class CIM_ExecutionRequirement : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The ConcreteCollection that is required to run the Job." )]
   CIM_ConcreteCollection REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Job that can be run." )]
   CIM_Job REF Dependent;


};
