// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_QueueStatisticalData 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::Processing" ), 
    Description ( 
       "The statistical data of a JobQueue. An instance of this class "
       "is associated with a specific JobQueue using the inherited "
       "ElementStatisticalData relationship." )]
class CIM_QueueStatisticalData : CIM_StatisticalData {

      [Description ( 
          "The number of Jobs whose MaxTimeOnQueue was exceeded. "
          "This would cause the Job to be removed from the Queue, "
          "and not processed to completion. This count begins at "
          "the time that the Queue was started/initialized." ), 
       Counter]
   uint64 JobsMaxTimeExceeded;

      [Description ( 
          "Specifies the current number of Jobs that are in the "
          "running state, for the related Queue." ), 
       Gauge]
   uint32 RunningJobs;

      [Description ( 
          "Specifies the current number of Jobs that are waiting to "
          "be put in the running state, for the related Queue." ), 
       Gauge]
   uint32 WaitingJobs;


};
