// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_FileShare 
// ==================================================================
   [Experimental, Abstract, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::FileElements" ), 
    Description ( 
       "A FileShare is representative of a LogicalFile presented for "
       "use (or shared) across systems. Instances of FileShare are "
       "associated with the shared object on the \'server\'-side via "
       "the CIM_SharedElement association. Shares are attached on the "
       "\'client\'-side (usually into another namespace) via the "
       "CIM_ImportedShare association. FileShare is Abstract to force "
       "subclassing to define the semantics of the file-sharing "
       "protocol. FileShare when used for importing deprecates "
       "RemoteFileSystem." )]
class CIM_FileShare : CIM_Share {

      [Description ( 
          "Indicates whether a directory or file is presented for "
          "use (or shared) across systems. A value of true "
          "represents a directory. A value of false represents a "
          "file." )]
   boolean SharingDirectory;


};
