// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_VirtualComputerSystem
// ==================================================================
   [Deprecated { "CIM_ComputerSystem" }, 
    Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::System::SystemElements" ), 
    Description ( 
       "A class derived from ComputerSystem that represents the "
       "ability to virtualize or emulate another ComputerSystem. \n"
       "The usage of this class is being deprecated in lieu of using "
       "ComputerSystem and the HostedDependency association." )]
class CIM_VirtualComputerSystem : CIM_ComputerSystem {

      [Deprecated { "No Value" }, 
       Description ( 
          "A string describing the type of System or hardware "
          "platform that is virtualized. OperatingSystem "
          "information is obtained via the RunningOS inherited from "
          "ComputerSystem." )]
   string VirtualSystem;


};
