// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_GenericDiskPartition 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Device::StorageExtents" ), 
    Description ( 
       "A DiskPartition is a presentation of a contiguous range of "
       "logical blocks that is identifiable by the Operating System by "
       "the associated DiskPartitionConfigurationCapabilities and by "
       "the properties of the subclasses of this class. \n"
       "\n"
       "Each concrete partition style (the subclasses of "
       "GenericDiskPartition) has some way of tracking a starting "
       "block number and either the ending block or number of blocks. "
       "CIM models this with the StartingAddress and EndingAddress "
       "properties of the BasedOn association between the partition "
       "and its underlying volume/extent. The NumberOfBlocks and "
       "ConsumableBlocks properties inherited from StorageExtent also "
       "need to be consistent or omitted by the instrumentation. "
       "Partition numbers are modeled as BasedOn.OrderIndex. \n"
       "\n"
       "Note that all the concrete DiskPartition instances BasedOn the "
       "same underlying extent) MUST share the same partition style "
       "(i.e. all must have the same subclass type). \n"
       "\n"
       "The abstract qualifier can not be used on this class because "
       "its superclass is not abstract. But instances of subclasses "
       "this class should be instantiated, not instances of "
       "GenericDiskPartition itself." )]
class CIM_GenericDiskPartition : CIM_MediaPartition {


};
