// Copyright (c) 2008 DMTF.  All rights reserved.
   [Experimental, Version ( "2.18.1" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( 
       "SerialPort is the logical representation of serial "
       "communications interface. It includes the setup or operation "
       "of the serial chips, at the lowest layers of a serial stack." )]
class CIM_SerialPort : CIM_LogicalPort {

      [Description ( "Number of stop bits to be transmitted." ), 
       PUnit ( "bit" )]
   uint16 NumberOfStopBits;

      [Description ( 
          "Information on the parity setting for transmitted data. "
          "A value set to 2 = \"None\" shall indicate that no "
          "parity bit value is provided. A value set to 3 = \"Even\" "
          "shall indicate that the parity is even. A value set to 4 "
          "= \"Odd\" shall indicate that the parity is odd." ), 
       ValueMap { "0", "2", "3", "4" }, 
       Values { "Unknown", "None", "Even", "Odd" }]
   uint16 ParityInfo;

      [Description ( 
          "An integer enumeration that indicates the flow control "
          "(Xon-Xoff or RTS/CTS) for transmitted data. A value set "
          "to 2 = \"Not Support\" shall indicate that flow control "
          "is not supported. A value set to 3 = \"XonXoff\" shall "
          "indicate that XonXoff is used for flow control. A value "
          "set to 4 = \"RTS/CTS\" shall indicate that RTS/CTS is "
          "used for flow control. A value set to 5 = \"Both XonXoff "
          "and RTS/CTS\" shall indicate that both XonXoff ans "
          "RTS/CTS are used for flow control." ), 
       ValueMap { "0", "2", "3", "4", "5" }, 
       Values { "Unknown", "Not Supported", "XonXoff", "RTS/CTS", 
          "Both XonXoff and RTS/CTS" }]
   uint16 FlowControlInfo;


};
