// Copyright (c) 2008 DMTF.  All rights reserved.
   [Version ( "2.19.0" ), 
    ClassConstraint { "inv: self.IsComposite=true" }, 
    UMLPackagePath ( "CIM::Device::StorageExtents" ), 
    Description ( 
       "A CompositeExtent is used to model the distribution of user "
       "data across one or more underlying StorageExtents, which may "
       "or not be protected by some redundancy mechanism. "
       "CompositeExtents represent a contiguous range of logical "
       "blocks. CompositeExtents may overlap, however, the underlying "
       "StorageExtents within the overlap shall not contain any check "
       "data. Distribution of check data may be specified using the "
       "CompositeExtentBasedOn association." )]
class CIM_CompositeExtent : CIM_StorageExtent {

      [Experimental, Override ( "IsComposite" ), 
       Description ( 
          "True indicates that the data is a composition of various "
          "StorageExtents that are associated to this StorageExtent "
          "via the CIM_CompositeBasedOnAssociation." )]
   boolean IsComposite = true;


};
