// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00688.005" type ="create">Added class
// ReplicaPoolForStorage.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ===================================================================
// CIM_ReplicaPoolForStorage
// ===================================================================
   [Association, Experimental, Version ( "2.9.1000" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( 
       "A specialized pool for replicas is associated exclusively to "
       "one source storage element or globally to the "
       "StorageConfigurationService. Such a pool is typically used to "
       "provide storage for delta replica space consumed in small "
       "chunks by replica elements. Elements representing the storage "
       "are not required to be made explicit." )]
class CIM_ReplicaPoolForStorage : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 0 ), 
       Max ( 1 ), 
       Description ( 
          "The source storage element or the StorageConfigurationService."
           )]
   CIM_EnabledLogicalElement REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The specialized replica pool." )]
   CIM_StoragePool REF Dependent;


};
