// Copyright (c) 2008 DMTF.  All rights reserved.
   [Experimental, Version ( "2.18.0" ), 
    Description ( 
       "StorageResourceLoadGroup aggregates either the StoragePools or "
       "the individual StorageVolumes that have the same affinity for "
       "a storage processor. The affinity of this group may change "
       "during failover or failback/rebind from one storage processor "
       "to another in a storage server. StorageResourceLoadGroup has a "
       "instance of the StorageProcessorAffinity association to each "
       "instance of CIM_ComputerSystem representing a storage "
       "processor that may host the StorageResourceLoadGroup in either "
       "a healthy or failover state. Each instance of "
       "StorageResourceLoadGroup in a storage server is also "
       "associated to each instance of TargetPortGroup in the server "
       "by the AsymmetricAccessibility class. There is an instance of "
       "CIM_HostedCollection associating the StorageResourceLoadGroup "
       "with the top-level CIM_ComputerSystem that aggregrates the "
       "storage processor ComputerSystem instances." )]
class CIM_StorageResourceLoadGroup : CIM_SystemSpecificCollection {


};
