// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_IBPortController 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Device::IB" ), 
    Description ( 
       "IBPortController is a logical device corresponding to an IB "
       "Channel Adapter (CA)." )]
class CIM_IBPortController : CIM_PortController {

      [Description ( 
          "The AdapterDiagnosticCode provides both generic and "
          "vendor- specific diagnostic functionality. For all "
          "ports, all bits set to zero means the port status is "
          "good. Any non-zero value means there are possible error "
          "conditions." ), 
       MappingStrings { "MAD.IBTA | PortInfo | DiagCode" }]
   uint32 AdapterDiagnosticCode;


};
