// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00734.006" type ="new">Added class.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_AGPVideoDisplayController
// ==================================================================
   [Experimental, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Controller" ), 
    Description ( 
       "Capabilities and management of an AGPVideoDisplayController." )]
class CIM_AGPVideoDisplayController : CIM_DisplayController {

      [Description ( "Size of the non-local video memory in KB." ), 
       Units ( "KiloBytes" ), 
       PUnit ( "byte * 2^10" )]
   uint32 NonlocalVideoMemorySize;

      [Description ( 
          "Width of the internal bus in the graphics Controller, in bits."
           ), 
       Units ( "Bits" ), 
       PUnit ( "bit" )]
   uint32 LocalBusWidth;

      [Description ( 
          "An integer enumeration indicating the usage model of the "
          "graphics Controller. Usage model indicates how the "
          "Controller does manipulations of graphics surfaces, "
          "textures, etc. in memory. DMA indicates that the "
          "graphics Controller brings structures from the system "
          "memory to its local memory to perform needed "
          "manipulations or renderings. Execute specifies that the "
          "graphics Controller can directly access a specified "
          "region in main memory (called the graphics aperture) "
          "using GART - Graphics Aperture Remapping Table. It then "
          "performs manipulations in that range as if that whole "
          "graphics aperture were part of its local memory. A value "
          "of \"Both\" DMA and Execute models may also be "
          "specified." ), 
       ValueMap { "0", "1", "2", "3", "4" }, 
       Values { "Unknown", "Other", "Execute", "DMA", "Both" }, 
       ModelCorrespondence { 
          "CIM_AGPVideoDisplayController.OtherUsageModel" }]
   uint16 UsageModel;

      [Description ( 
          "A string describing the usage mode when the instance\'s "
          "UsageModel property is 1 (\"Other\")." ), 
       ModelCorrespondence { 
          "CIM_AGPVideoDisplayController.UsageModel" }]
   string OtherUsageModel;

      [Description ( 
          "An integer enumeration indicating the data transfer rate "
          "of the graphics Controller." ), 
       ValueMap { "0", "1", "2", "3", "4", "5" }, 
       Values { "Unknown", "Other", "1X", "2X", "4X", "8X" }, 
       ModelCorrespondence { 
          "CIM_AGPVideoDisplayController.OtherDataTransferRate" }]
   uint16 DataTransferRate;

      [Description ( 
          "A string describing the data transfer rate when the "
          "instance\'s DataTransferRate property is 1 (\"Other\")." ), 
       ModelCorrespondence { 
          "CIM_AGPVideoDisplayController.DataTransferRate" }]
   string OtherDataTransferRate;

      [Description ( 
          "An integer enumeration indicating the addressing mode of "
          "the graphics Controller." ), 
       ValueMap { "0", "1", "2", "3" }, 
       Values { "Unknown", "Other", "Sideband", "Pipeline" }, 
       ModelCorrespondence { 
          "CIM_AGPVideoDisplayController.OtherAddressingMode" }]
   uint16 AddressingMode;

      [Description ( 
          "A string describing the addressing mode when the "
          "instance\'s AddressingMode property is 1 (\"Other\")." ), 
       ModelCorrespondence { 
          "CIM_AGPVideoDisplayController.AddressingMode" }]
   string OtherAddressingMode;

      [Description ( 
          "The maximum number of AGP Transaction requests that the "
          "master (AGP Graphics Controller) is allowed to enqueue "
          "into the target." )]
   uint32 MaximumAGPCommandQueuePath;

      [Description ( 
          "The number of AGP Transaction that the core logic "
          "(chipset) can accept into its transaction request queue "
          "from the Controller." )]
   uint32 MaxNumberOfPipelinedAGPTransactions;

      [Description ( "Size of the graphics aperture in KB." ), 
       Units ( "KiloBytes" ), 
       PUnit ( "byte * 2^10" )]
   uint32 GraphicsApertureSize;

      [Description ( 
          "A string containing the AGP specification version to "
          "which this graphics Controller conforms." )]
   string AGPSpecificationVersionConformance;


};
