// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_WirelessPort 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( "Capabilities and management of a wireless port." )]
class CIM_WirelessPort : CIM_NetworkPort {

      [Override ( "PortType" ), 
       Description ( "The type of port." ), 
       ValueMap { "0", "1", "75", "76", "77", "78", "79", "80", 
          "16000.." }, 
       Values { "Unknown", "Other", "Client Station", "Repeater", 
          "Access Point", "Bridge Host", "Bridge", "Bridge Root", 
          "Vendor Reserved" }]
   uint16 PortType;

      [Description ( 
          "The current signal strength is a percentage of the total "
          "signal strength. For example, if the current signal "
          "strength is 3 bars out of 5, the property would hold the "
          "value, 60." ), 
       Units ( "Percentage" ), 
       MinValue ( 0 ), 
       MaxValue ( 100 ), 
       PUnit ( "percent" )]
   uint8 SignalStrength;


};
