// Copyright (c) 2008 DMTF.  All rights reserved.
   [Experimental, Version ( "2.18.0" ), 
    Description ( 
       "TargetPortGroup aggregates the ProtocolEndpoints representing "
       "a group of target ports in a storage server. The "
       "ProtocolEndpoints may be a subclass of CIM_ProtocolEndpoint as "
       "appropriate for the type of target port implemented by the "
       "storage server. The target ports are aggregated because they "
       "have the same affinity for an associated storage processor for "
       "failover and the same accessibility state to storage resources "
       "in a given StorageResourceLoadGroup. The TargetPortGroup may "
       "have either a fixed affinity for a storage processor within "
       "the server or an affinity that changes during failover from "
       "one storage processors to another. TargetPortGroup has a "
       "instance of the StorageProcessorAffinity association to each "
       "instance of CIM_ComputerSystem representing a storage "
       "processor that may host the TargetPortGroup in either a "
       "healthy or failover state. Each instance of TargetPortGroup in "
       "a storage server is also associated to each instance of "
       "StorageResourceLoadGroup in the server by the "
       "AsymmetricAccessibility class. There is an instance of "
       "CIM_HostedCollection associating the StorageResourceLoadGroup "
       "with the top-level CIM_ComputerSystem that aggregates the "
       "storage processor ComputerSystem instances." )]
class CIM_TargetPortGroup : CIM_SystemSpecificCollection {


};
