// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SMWGCR00068" type ="change">Promote
// the Dependent association to ManagedSystemElement.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AssociatedSensor 
// ==================================================================
   [Association, Version ( "2.12.0" ), 
    UMLPackagePath ( "CIM::Device::Sensors" ), 
    Description ( 
       "The CIM_AssociatedCooling relationship indicates what "
       "ManagedSystemElement(s) the fan or cooling device is "
       "providingcooling for." )]
class CIM_AssociatedSensor : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Sensor." )]
   CIM_Sensor REF Antecedent;

      [Experimental, Override ( "Dependent" ), 
       Description ( 
          "The ManagedSystemElement for which information is "
          "measured by the Sensor." )]
   CIM_ManagedSystemElement REF Dependent;


};
