// Copyright (c) 2008 DMTF.  All rights reserved.
   [Association, Experimental, Version ( "2.18.1" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( 
       "This association indicates the accessibility of StorageVolumes "
       "in the StorageResourceLoadGroup through ports in the "
       "associated TargetPortGroup." )]
class CIM_AsymmetricAccessibility : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Port Group." )]
   CIM_TargetPortGroup REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Storage Resource Load Group." )]
   CIM_StorageResourceLoadGroup REF Dependent;

      [Description ( 
          "This property indicates the current accessibility state "
          "of volumes in the StorageResourceLoadGroup through ports "
          "in the TargetPortGroup. With the exception of "
          "\'Unavailable\', the states are those defined by the T10 "
          "SPC-4 Target Port Group Access States clause. "
          "2(Unavailable): The volumes are not accessible in any "
          "way. 3(Standby): No data access to the volume is "
          "possible. Status and other non-data access commands are "
          "available. 4(Active Non-Optimized): Data access to the "
          "volume is available at less than full bandwidth. "
          "5(Active Optimized): Data access to the volume is "
          "available at full bandwidth." ), 
       ValueMap { "2", "3", "4", "5" }, 
       Values { "Unavailable", "Standby", "Active Non-Optimized", 
          "Active Optimized" }]
   uint16 CurrentAccessState;

      [Description ( 
          "This property indicates the normal accessibility state "
          "of volumes in the StorageResourceLoadGroup through ports "
          "in the TargetPortGroup when the primary storage "
          "processor hosting the groups is healthy. With the "
          "exception of \'Unavailable\', the states are those "
          "defined by the T10 SPC-4 Target Port Group Access States "
          "clause. 2(Unavailable): The volumes are not accessible. "
          "3(Standby): No data access to the volume is possible. "
          "Status and other non-data access commands are available. "
          "4(Active Non-Optimized): Data access to the volume is "
          "available at less than full bandwidth. 5(Active "
          "Optimized): Data access to the volume is available at "
          "full bandwidth." ), 
       ValueMap { "2", "3", "4", "5" }, 
       Values { "Unavailable", "Standby", "Active Non-Optimized", 
          "Active Optimized" }]
   uint16 NormalAccessState;


};
