// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_InstalledPartitionTable 
// ==================================================================
   [Association, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Device::StorageExtents" ), 
    Description ( 
       "This association describes the attributes of a partition table "
       "installed in an extent. The attributes are in the capabilities "
       "class." )]
class CIM_InstalledPartitionTable : CIM_Dependency {

      [Experimental, Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "The DiskPartitionConfigurationCapabilities describing "
          "the capabilities of partitions based on this extent." )]
   CIM_DiskPartitionConfigurationCapabilities REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The extent \'hosting\' the partitions \n." )]
   CIM_StorageExtent REF Dependent;


};
