// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ATAPort 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Device::Ports" ), 
    Description ( 
       "Represents the port of an ATA device to system connection." )]
class CIM_ATAPort : CIM_LogicalPort {

      [Override ( "PortType" ), 
       Description ( "The type of port." ), 
       ValueMap { "0", "1", "91", "92", "93", "16000.." }, 
       Values { "Unknown", "Other", "ATA", "SATA", "SATA2", 
          "Vendor Reserved" }]
   uint16 PortType;


};
