//Copyright (c) 2007 DMTF. All Rights Reserved.
   [Association, Experimental, Version ( "2.17.0" ), 
    UMLPackagePath ( "CIM::Device::Printing" ), 
    Description ( 
       "This class represents the association between a PrintSupply "
       "component of a Printer (print device) and a PrintMarker or "
       "PrintFinisher component of the same Printer. Note: A "
       "PrintSupply shall be associated with exactly one PrintMarker "
       "or PrintFinisher. See: Model in section 2 of Printer MIB (RFC "
       "3805) and section 3 of Finisher MIB (RFC 3806)." ), 
    MappingStrings { 
       "MIB.IETF|Printer-MIB.prtMarkerSuppliesMarkerIndex", 
       "MIB.IETF|Finisher-MIB.finSupplyDeviceIndex" }]
class CIM_AssociatedPrintSupply : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The PrintSupply (e.g., toner cartridge or staples) "
          "component of a Printer." )]
   CIM_PrintSupply REF Antecedent;

      [Override ( "Dependent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The PrintMarker or PrintFinisher component of the same "
          "Printer that needs or is associated with this "
          "PrintSupply." )]
   CIM_PrinterElement REF Dependent;


};
