// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_IBPortStatistics 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Device::IB" ), 
    Description ( 
       "The class, IBPortStatistics, represents the statistics for the "
       "IBPort." )]
class CIM_IBPortStatistics : CIM_NetworkPortStatistics {

      [Description ( 
          "Total number of symbol errors detected on one or more VLs."
           ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | SymbolErrorCounter" }]
   uint16 SymbolErrorCounter;

      [Description ( 
          "Total number of times the Port Training state machine "
          "has successfully completed the link error recovery "
          "process." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | LinkErrorRecoveryCounter" }]
   uint16 LinkErrorRecoveryCounter;

      [Description ( 
          "Total number of times the Port Training state machine "
          "has failed the link error recovery process and downed "
          "the link." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | LinkDownedCounter" }]
   uint16 LinkDownedCounter;

      [Description ( 
          "Total number of packets containing an error that were "
          "received on the port." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | PortRcvErrors" }]
   uint16 PortRcvErrors;

      [Description ( 
          "Total number of packets marked with the EBP delimiter "
          "received on the port." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | PortRcvRemotePhysicalErrors" }]
   uint16 PortRcvRemotePhysicalErrors;

      [Description ( 
          "Total number of packets received on the port that were "
          "discarded because they could not be forwarded by the "
          "switch relay." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | PortRcvSwitchRelayErrors" }]
   uint16 PortRcvSwitchRelayErrors;

      [Description ( 
          "Total number of outbound packets discarded by the port "
          "because the port is down or congested." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | PortXmitDiscards" }]
   uint16 PortXmitDiscards;

      [Description ( 
          "Total number of packets not transmitted from the port "
          "for any of the following reasons: \n"
          "- FilterRawOutbound is true and packet is raw \n"
          "- PartitionEnforcementOutbound is true and packet fails "
          "partition key check, IP version check, or \n"
          "transport header version check." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | PortXmitConstraintErrors" }]
   uint16 PortXmitConstraintErrors;

      [Description ( 
          "Total number of packets received on the port that are "
          "discarded for any of the following reasons: \n"
          "- FilterRawInbound is true and packet is raw - "
          "PartitionEnforcementInbound is true and packet fails "
          "partition key check, IP version check, or transport "
          "header version check." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | PortRcvConstraintErrors" }]
   uint16 PortRcvConstraintErrors;

      [Description ( 
          "The number of times that the frequency of packets "
          "containing local physical errors exceeded the local "
          "physical error threshold." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | LocalLinkIntegrityErrors" }]
   uint16 LocalLinkIntegrityErrors;

      [Description ( 
          "The number of times that consecutive flow control update "
          "periods had at least one overrun error." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | ExcessiveBufferOverrunErrors" }]
   uint16 ExcessiveBufferOverrunErrors;

      [Description ( 
          "Number of incoming VL15 packets dropped due to resource "
          "limitations (due to lack of buffers)." ), 
       Counter, MappingStrings { 
          "MAD.IBTA | PortCounters | VL15Dropped" }]
   uint16 VL15Dropped;


};
