// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="sysdevCR00679_003" type = "create"> Add CIM_StorageLibraryCapabilities.</change> 
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
// StorageLibraryCapabilities
// ==================================================================
   [Experimental, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::StorageLib" ), 
    Description ( "Capabilities of Storage Library systems." )]
class CIM_StorageLibraryCapabilities : CIM_Capabilities {

      [Description ( 
          "Capabilities of the Storage Library. For example, "
          "whether it can perform automatic cleaning of the "
          "MediaAccessDevices contained in it (value=2) or that "
          "Front Panel is lockable (value=4)." ), 
       ValueMap { "0", "2", "3", "4" }, 
       Values { "Unknown", "Automatic Cleaning", "Manual Operation", 
          "Front Panel Lockable" }]
   uint16 Capabilities[];

      [Description ( 
          "Maximum time in seconds that it takes for the Media "
          "Library to perform a complete audit of each StorageMedia "
          "Location, to determine the absence or presence of a "
          "Physical Media. If automated support is not provided, "
          "then this property\'s value is undefined." ), 
       Units ( "Seconds" ), 
       PUnit ( "second" )]
   uint64 MaxAuditTime;


};
