// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00735.001" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="CIMCoreCR00734.006" type ="deprecate">Deprecate class.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_AGPVideoController
// ==================================================================
   [Deprecated { "CIM_AGPVideoDisplayController" }, 
    Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Device::Controller" ), 
    Description ( 
       "Note: The use of the CIM_AGPVideoController class has been "
       "deprecated in lieu of CIM_AGPVideoDisplayController. \n"
       "Deprecated description: \n"
       "Capabilities and management of an AGPVideoController." )]
class CIM_AGPVideoController : CIM_VideoController {

      [Deprecated { "No Value" }, 
       Description ( 
          "Note: The use of the CIM_AGPVideoController class has "
          "been deprecated in lieu of "
          "CIM_AGPVideoDisplayController. \n"
          "Deprecated description: \n"
          "Deprecated description: Capabilities of the AGP Graphics "
          "Controller. For example, the Device might support "
          "multiple monitors, PCI Mastering, and large memory "
          "addresses. In this case, the values 3, 4, and 6 would be "
          "written to the Capabilities array." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "6" }, 
       Values { "Unknown", "Other", "PCI Fast Write", 
          "MultiMonitor Support", "PCI Mastering", 
          "Second Monochrome Adapter Support", 
          "Large Memory Address Support" }, 
       ArrayType ( "Indexed" ), 
       ModelCorrespondence { 
          "CIM_AGPVideoController.CapabilityDescriptions" }]
   uint16 Capabilities[];

      [Deprecated { 
          "CIM_AGPVideoDisplayController.NonlocalVideoMemorySize" }, 
       Description ( "Size of the non-local video memory in KB." ), 
       Units ( "KiloBytes" ), 
       PUnit ( "byte * 2^10" )]
   uint32 NonlocalVideoMemorySize;

      [Deprecated { "CIM_AGPVideoDisplayController.LocalBusWidth" }, 
       Description ( 
          "Width of the internal bus in the graphics Controller, in bits."
           ), 
       Units ( "Bits" ), 
       PUnit ( "bit" )]
   uint32 LocalBusWidth;

      [Deprecated { "CIM_AGPVideoDisplayController.UsageModel" }, 
       Description ( 
          "An integer enumeration that indicates the usage model of "
          "the graphics Controller. The usage model indicates how "
          "the Controller does manipulations of graphics surfaces, "
          "textures, and so on in memory. DMA indicates that the "
          "graphics Controller brings structures from the system "
          "memory to its local memory to perform needed "
          "manipulations or renderings. Execute specifies that the "
          "Graphics Controller can directly access a specified "
          "region in main memory (called the graphics aperture) "
          "using GART (Graphics Aperture Remapping Table). It then "
          "performs manipulations in that range as if that whole "
          "graphics aperture were part of its local memory. A value "
          "of \"Both\" DMA and Execute models can also be "
          "specified." ), 
       ValueMap { "0", "1", "2", "3", "4" }, 
       Values { "Unknown", "Other", "Execute", "DMA", "Both" }]
   uint16 UsageModel;

      [Deprecated { "CIM_AGPVideoDisplayController.DataTransferRate" }, 
       Description ( 
          "An integer enumeration that indicates the data transfer "
          "rate of the graphics Controller." ), 
       ValueMap { "0", "1", "2", "3", "4" }, 
       Values { "Unknown", "Other", "1X", "2X", "4X" }]
   uint16 DataTransferRate;

      [Deprecated { "CIM_AGPVideoDisplayController.AddressingMode" }, 
       Description ( 
          "An integer enumeration that indicates the addressing "
          "mode of the graphics Controller." ), 
       ValueMap { "0", "1", "2", "3" }, 
       Values { "Unknown", "Other", "Sideband", "Pipeline" }]
   uint16 AddressingMode;

      [Deprecated { 
          "CIM_AGPVideoDisplayController.MaximumAGPCommandQueuePath" }, 
       Description ( 
          "The maximum number of AGP Transaction requests that the "
          "master (AGP Graphics Controller) is allowed to enqueue "
          "into the target." )]
   uint32 MaximumAGPCommandQueuePath;

      [Deprecated { 
          "CIM_AGPVideoDisplayController.MaxNumberOfPipelinedAGPTransactions" }, 
       Description ( 
          "The number of AGP Transaction that the core logic (chip "
          "set) can accept into its transaction request queue from "
          "the Controller." )]
   uint32 MaxNumberOfPipelinedAGPTransactions;

      [Deprecated { 
          "CIM_AGPVideoDisplayController.GraphicsApertureSize" }, 
       Description ( "Size of the graphics aperture in KB." ), 
       Units ( "KiloBytes" ), 
       PUnit ( "byte * 2^10" )]
   uint32 GraphicsApertureSize;

      [Deprecated { 
          "CIM_AGPVideoDisplayController.AGPSpecificationVersionConformance" }, 
       Description ( 
          "A string that contains the AGP specification version to "
          "which this graphics Controller conforms." )]
   string AGPSpecificationVersionConformance;


};
