// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_StorageNameBindingService
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Device::StorageNameBinding" ), 
    Description ( "Provides functions needed for name binding." )]
class CIM_StorageNameBindingService : CIM_Service {


      [Description ( 
          "This method requests that the driver create a name "
          "binding from a target (and option logical unit) and lets "
          "the OS assign the name." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "..", "32768..65535" }, 
       Values { "Success", "Not Supported", "Unknown", "Timeout", 
          "Failed", "Invalid Parameter", "DMTF Reserved", 
          "Vendor Specific" }]
   uint32 CreateStorageNameBinding(
         [IN, Description ( "The value to assign to BindingType." ), 
          ValueMap { "2", "3", "4", "5", "6", "7" }, 
          Values { "FcApiBindToDID", "FcApiBindToWWPN", 
             "FcApiBindToWWNN", "BindToLUID", 
             "iSCSI Target Name", "iSCSI Network Address" }]
      uint16 BindingType, 
         [IN, Description ( 
             "The value to assign to BindAllLogicalUnits." )]
      boolean BindAllLogicalUnits, 
         [IN, Description ( "The value to assign to Hide." )]
      boolean Hide, 
         [IN, Description ( "The value to assign to TargetName." )]
      string TargetName, 
         [IN, Description ( 
             "The value to assign to LogicalUnitNumber." )]
      string LogicalUnitNumber, 
         [IN, Description ( 
             "The type of the port in LocalPortName." ), 
          ValueMap { "2", "3" }, 
          Values { "FC Port WWN", "iSCSI Name" }]
      uint16 LocalPortNameType, 
         [IN, Description ( 
             "The value to assign to LocalPortName." ), 
          ModelCorrespondence { 
             "CIM_StorageNameBinding.LocalPortNameType" }]
      string LocalPortName, 
         [IN ( false ), OUT, Description ( 
             "A reference to the created name binding instance." )]
      CIM_StorageNameBinding REF Binding);

      [Description ( 
          "This method requests that the driver create a name "
          "binding from a target (and option logical unit) to a "
          "specified OS Device Name or addresses." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "..", "32768..65535" }, 
       Values { "Success", "Not Supported", "Unknown", "Timeout", 
          "Failed", "Invalid Parameter", "DMTF Reserved", 
          "Vendor Specific" }]
   uint32 CreateOSStorageNameBinding(
         [IN, Description ( "The value to assign to BindingType." ), 
          ValueMap { "2", "3", "4", "5", "6", "7" }, 
          Values { "FcApiBindToDID", "FcApiBindToWWPN", 
             "FcApiBindToWWNN", "BindToLUID", 
             "iSCSI Target Name", "iSCSI Network Address" }]
      uint16 BindingType, 
         [IN, Description ( 
             "The value to assign to BindAllLogicalUnits." )]
      boolean BindAllLogicalUnits, 
         [IN, Description ( "The value to assign to Hide." )]
      boolean Hide, 
         [IN, Description ( "The value to assign to TargetName." )]
      string TargetName, 
         [IN, Description ( 
             "The value to assign to LogicalUnitNumber." )]
      string LogicalUnitNumber, 
         [IN, Description ( 
             "The value to assign to OSDeviceName." )]
      string OSDeviceName, 
         [IN, Description ( 
             "The value to assign to OSAddressesValid." )]
      boolean OSAddressesValid, 
         [IN, Description ( "The value to assign to OSBusNumber." )]
      uint32 OSBusNumber, 
         [IN, Description ( 
             "The value to assign to OSTargetNumber." )]
      uint32 OSTargetNumber, 
         [IN, Description ( "The value to assign to OSLUN." )]
      uint32 OSLUN, 
         [IN ( false ), OUT, Description ( 
             "A reference to the created name binding instance." )]
      CIM_StorageNameBinding REF Binding);

      [Description ( 
          "This method requests that the driver create a name "
          "binding between real and virtual initiator names on a "
          "bridge." ), 
       ValueMap { "0", "1", "2", "3", "4", "5", "..", "32768..65535" }, 
       Values { "Success", "Not Supported", "Unknown", "Timeout", 
          "Failed", "Invalid Parameter", "DMTF Reserved", 
          "Vendor Specific" }]
   uint32 CreateStorageBridgeNameBinding(
         [IN, Description ( "The value to assign to BindingType." ), 
          ValueMap { "2", "3", "4", "5", "6", "7" }, 
          Values { "FcApiBindToDID", "FcApiBindToWWPN", 
             "FcApiBindToWWNN", "BindToLUID", 
             "iSCSI Target Name", "iSCSI Network Address" }]
      uint16 BindingType, 
         [IN, Description ( 
             "The value to assign to BindAllLogicalUnits." )]
      boolean BindAllLogicalUnits, 
         [IN, Description ( "The value to assign to Hide." )]
      boolean Hide, 
         [IN, Description ( "The value to assign to TargetName." )]
      string TargetName, 
         [IN, Description ( 
             "The value to assign to InitiatorPortName." )]
      string InitiatorPortName, 
         [IN, Description ( 
             "The value to assign to InitiatorPortNameType." ), 
          ValueMap { "2", "3", "4" }, 
          Values { "FibreChannel Port WWN", 
             "SRP Port Identifier", "iSCSI Name" }]
      uint16 InitiatorPortNameType, 
         [IN, Description ( 
             "The value to assign to AssignedPortName." )]
      string AssignedPortName, 
         [IN, Description ( 
             "The value to assign to AssignedPortNameType." ), 
          ValueMap { "2", "3", "4" }, 
          Values { "FibreChannel Port WWN", 
             "SRP Port Identifier", "iSCSI Name" }]
      uint16 AssignedPortNameType, 
         [IN ( false ), OUT, Description ( 
             "A reference to the created name binding instance." )]
      CIM_StorageNameBinding REF Binding);

};
