// Copyright (c) 2008 DMTF.  All rights reserved.
   [Association, Experimental, Aggregation, Version ( "2.19.0" ), 
    UMLPackagePath ( "CIM::Device::Printing" ), 
    Description ( 
       "PrinterComponent is a specialization of the Component "
       "aggregation that establishes \'part of\' relationships between "
       "a scoping Printer (print device) and each of the "
       "PrinterElements of which it is composed. \n"
       "Note: A Printer shall be associated with at least one of every "
       "required component (e.g., PrintMarker) via an instance of the "
       "PrinterComponent class. A Printer may be associated with zero "
       "or more optional components (e.g., PrintSupply) via an "
       "instance of the ConcreteComponent class. See: Model in section "
       "2 of Printer MIB (RFC 3805) and section 3 of Finisher MIB (RFC "
       "3806)." )]
class CIM_PrinterComponent : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The parent Printer in the Association." )]
   CIM_Printer REF GroupComponent;

      [Override ( "PartComponent" ), 
       Min ( 1 ), 
       Description ( 
          "The child PrinterElement that is a component of this Printer."
           )]
   CIM_PrinterElement REF PartComponent;


};
