// Copyright (c) 2006 DMTF.  All rights reserved.
// <change cr="DBCR00030" type ="add">Add top level relational model
// support to the database model.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ===================================================================
// CIM_SqlDomain
// ===================================================================
   [Experimental, Version ( "2.12.0" ), 
    UMLPackagePath ( "CIM::Database::Sql" ), 
    Description ( 
       "A domain is a set of permissible values. A domain is defined "
       "in a schema and is identified by a <domain name>. The purpose "
       "of a domain is to constrain the set of valid values that can "
       "be stored in a column of a base table by various operations. \n"
       "\n"
       "A domain definition specifies a data type. It may also specify "
       "a <domain constraint> that further restricts the valid values "
       "of the domain and a <default clause> that specifies the value "
       "to be used in the absence of an explicitly specified value or "
       "column default. \n"
       "\n"
       "A domain is described by a domain descriptor. A domain "
       "descriptor includes: \n"
       "- The name of the domain. \n"
       "- The data type descriptor of the data type of the domain. \n"
       "- The value of <default option>, if any, of the domain. \n"
       "- The domain constraint descriptors of the domain constraints, "
       "if any, of the domain." )]
class CIM_SqlDomain : CIM_SqlObject {

      [Description ( 
          "A data type is a set of representable values. Every "
          "representable value belongs to at least one data type "
          "and some belong to several data types. \n"
          "\n"
          "Every predefined data type is a subtype of itself and of "
          "no other data types. It follows that every predefined "
          "data type is a supertype of itself and of no other data "
          "types." ), 
       ValueMap { "2", "3", "4", "5", "6", "7", "8", "9", "10", 
          "11", "12", "13", "14", "15", "16", "17", "18", "19", 
          "20", "21", "22", "23", "24", "25", "26..32767", 
          "32768..65535" }, 
       Values { "CHARACTER", "CHARACTER_VARYING", 
          "CHARACTER_LARGE_OBJECT", "NATIONAL_CHARACTER", 
          "NATIONAL_CHARACTER_VARYING", 
          "NATIONAL_CHARACTER_LARGE_OBJECT", "BINARY", 
          "BINARY_VARYING", "BINARY_LARGE_OBJECT", "NUMERIC", 
          "DECIMAL", "SMALLINT", "INTEGER", "BIGINT", "FLOAT", 
          "REAL", "DOUBLE_PRECISION", "BOOLEAN", "DATE", "TIME", 
          "TIMESTAMP", "INTERVAL", "DATALINK", "XML_TYPE", 
          "DMTF Reserved", "Vendor Reserved" }]
   uint16 DataType;

      [Description ( 
          "The value to be used in the absence of an explicitly "
          "specified value or column default." )]
   string DefaultValue;


};
