// Copyright (c) 2006 DMTF.  All rights reserved.
// <change cr="DBCR00030" type ="add">Add top level relational model
// support to the database model.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ===================================================================
// CIM_SqlDomainConstraint
// ===================================================================
   [Experimental, Version ( "2.12.0" ), 
    UMLPackagePath ( "CIM::Database::Sql" ), 
    Description ( 
       "A domain constraint is a constraint that is specified for a "
       "domain. It is applied to all columns that are based on that "
       "domain, and to all values cast to that domain. A domain "
       "constraint is described by a domain constraint descriptor. In "
       "addition to the components of every constraint descriptor a "
       "domain constraint descriptor includes: \n"
       "- The <search condition>. \n"
       "\n"
       "A domain constraint is satisfied by SQL-data if and only if, "
       "for any table T that has a column named C based on that "
       "domain, the specified <search condition>, with each occurrence "
       "of VALUE replaced by C, is not False for any row of T. A "
       "domain constraint is satisfied by the result of a <cast "
       "specification> if and only if the specified <search "
       "condition>, with each occurrence of VALUE replaced by that "
       "result, is not False." )]
class CIM_SqlDomainConstraint : CIM_SqlDomain {

      [Description ( 
          "The value of the <search condition>, if any, for this "
          "Domain Constraint." )]
   string SearchCondition;


};
