// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DBCR00028" type ="change">CPubs edits to the database software resource classes.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SWRDatabaseAspect 
// ==================================================================
   [Association, Experimental, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Database::SWResources" ), 
    Description ( 
       "SWRDatabaseAspect is the association between multiple database "
       "software resources (for instance, the aspects) and the one "
       "database (mostly a couple of files) controlled by the "
       "operating system." )]
class CIM_SWRDatabaseAspect : CIM_SWRManageableAspect {

      [Override ( "SystemElement" ), 
       Description ( 
          "The common database, which is viewed as software resource."
           )]
   CIM_CommonDatabase REF SystemElement;

      [Override ( "SameElement" ), 
       Description ( 
          "SameElement is the aspect: the software resource \'Database\'."
           )]
   CIM_SWRDatabase REF SameElement;


};
