#pragma include ("dri/DRI_Account.mof") 
#pragma include ("dri/DRI_AccountAssignedIdentity.mof") 
#pragma include ("dri/DRI_AccountElementCapabilities.mof") 
#pragma include ("dri/DRI_AccountManagementCapabilities.mof") 
#pragma include ("dri/DRI_AccountManagementService.mof") 
#pragma include ("dri/DRI_AccountOnSystem.mof") 
#pragma include ("dri/DRI_AccountSettingData.mof") 
#pragma include ("dri/DRI_AlertIndication.mof") 
#pragma include ("dri/DRI_AssignedIdentity.mof") 
#pragma include ("dri/DRI_AssociatedCacheMemory.mof") 
#pragma include ("dri/DRI_AssociatedCooling.mof") 
#pragma include ("dri/DRI_AssociatedPowerManagementService.mof") 
#pragma include ("dri/DRI_AssociatedSensor.mof") 
#pragma include ("dri/DRI_BasedOn.mof") 
#pragma include ("dri/DRI_Battery.mof") 
#pragma include ("dri/DRI_BindsTo.mof") 
#pragma include ("dri/DRI_BindsToLANEndpoint.mof") 
#pragma include ("dri/DRI_BIOSAttribute.mof") 
#pragma include ("dri/DRI_BIOSConcreteCollection.mof") 
#pragma include ("dri/DRI_BIOSConcreteComponent.mof") 
#pragma include ("dri/DRI_BIOSElement.mof") 
#pragma include ("dri/DRI_BIOSEnumeration.mof") 
#pragma include ("dri/DRI_BIOSInteger.mof") 
#pragma include ("dri/DRI_BIOSOrderedMemberOfCollection.mof") 
#pragma include ("dri/DRI_BIOSOwningCollectionElement.mof") 
#pragma include ("dri/DRI_BIOSPassword.mof") 
#pragma include ("dri/DRI_BIOSService.mof") 
#pragma include ("dri/DRI_BIOSServiceAffectsElement.mof") 
#pragma include ("dri/DRI_BIOSServiceCapabilities.mof") 
#pragma include ("dri/DRI_BIOSString.mof") 
#pragma include ("dri/DRI_BootConfigSetting.mof") 
#pragma include ("dri/DRI_BootService.mof") 
#pragma include ("dri/DRI_BootServiceCapabilities.mof") 
#pragma include ("dri/DRI_BootSettingData.mof") 
#pragma include ("dri/DRI_BootSourceSetting.mof") 
#pragma include ("dri/DRI_BootSourceSettingOrderedComponent.mof") 
#pragma include ("dri/DRI_Card.mof") 
#pragma include ("dri/DRI_CDROMDrive.mof") 
#pragma include ("dri/DRI_Chassis.mof") 
#pragma include ("dri/DRI_Chip.mof") 
#pragma include ("dri/DRI_ComputerSystem.mof") 
#pragma include ("dri/DRI_ComputerSystemPackage.mof") 
#pragma include ("dri/DRI_ConcreteComponent.mof") 
#pragma include ("dri/DRI_ConcreteDependency.mof") 
#pragma include ("dri/DRI_ConfigService.mof") 
#pragma include ("dri/DRI_ConfigurationCapacity.mof") 
#pragma include ("dri/DRI_ConnectedTo.mof") 
#pragma include ("dri/DRI_Container.mof") 
#pragma include ("dri/DRI_DeviceSAPImplementation.mof") 
#pragma include ("dri/DRI_DHCPCapabilities.mof") 
#pragma include ("dri/DRI_DHCPProtocolEndpoint.mof") 
#pragma include ("dri/DRI_DHCPSettingData.mof") 
#pragma include ("dri/DRI_DiagService.mof") 
#pragma include ("dri/DRI_DNSGeneralSettingData.mof") 
#pragma include ("dri/DRI_DNSProtocolEndpoint.mof") 
#pragma include ("dri/DRI_DNSSettingData.mof") 
#pragma include ("dri/DRI_ElementCapabilities.mof") 
#pragma include ("dri/DRI_ElementCapabilitiesInterop.mof") 
#pragma include ("dri/DRI_ElementCapacity.mof") 
#pragma include ("dri/DRI_ElementConformsToProfile.mof") 
#pragma include ("dri/DRI_ElementSettingData.mof") 
#pragma include ("dri/DRI_ElementSoftwareIdentity.mof") 
#pragma include ("dri/DRI_EnabledLogicalElementCapabilities.mof") 
#pragma include ("dri/DRI_EthernetPort.mof") 
#pragma include ("dri/DRI_Fan.mof") 
#pragma include ("dri/DRI_FanRedundancySet.mof") 
#pragma include ("dri/DRI_Group.mof") 
#pragma include ("dri/DRI_HardwareThread.mof") 
#pragma include ("dri/DRI_HostedAccessPoint.mof") 
#pragma include ("dri/DRI_HostedCollection.mof") 
#pragma include ("dri/DRI_HostedService.mof") 
#pragma include ("dri/DRI_Identity.mof") 
#pragma include ("dri/DRI_IdentityContext.mof") 
#pragma include ("dri/DRI_IdentityMemberOfCollection.mof") 
#pragma include ("dri/DRI_IdentityServiceAffectsElement.mof") 
#pragma include ("dri/DRI_IdentityUsesOpaqueManagementData.mof") 
#pragma include ("dri/DRI_IndicationService.mof") 
#pragma include ("dri/DRI_IndicationServiceAffectsElement.mof") 
#pragma include ("dri/DRI_IndicationServiceCapabilities.mof") 
#pragma include ("dri/DRI_InstalledOS.mof") 
#pragma include ("dri/DRI_InstalledSoftwareIdentity.mof") 
#pragma include ("dri/DRI_IPAssignmentSettingData.mof") 
#pragma include ("dri/DRI_IPConfigurationService.mof") 
#pragma include ("dri/DRI_IPElementSettingData.mof") 
#pragma include ("dri/DRI_IPProtocolEndpoint.mof") 
#pragma include ("dri/DRI_IPRemoteAccessAvailableToElement.mof") 
#pragma include ("dri/DRI_IPRemoteServiceAccessPoint.mof") 
#pragma include ("dri/DRI_IsSpare.mof") 
#pragma include ("dri/DRI_LANEndpoint.mof") 
#pragma include ("dri/DRI_ListenerDestinationWsMan.mof") 
#pragma include ("dri/DRI_LogicalDevice.mof") 
#pragma include ("dri/DRI_LogicalDisk.mof") 
#pragma include ("dri/DRI_LogicalIdentity.mof") 
#pragma include ("dri/DRI_MemberOfCollection.mof") 
#pragma include ("dri/DRI_Memory.mof") 
#pragma include ("dri/DRI_NetworkPort.mof") 
#pragma include ("dri/DRI_NetworkPortConfigurationService.mof") 
#pragma include ("dri/DRI_NumericSensor.mof") 
#pragma include ("dri/DRI_OmdServiceAffectsElement.mof") 
#pragma include ("dri/DRI_OpaqueManagementData.mof") 
#pragma include ("dri/DRI_OpaqueManagementDataCapabilities.mof") 
#pragma include ("dri/DRI_OpaqueManagementDataService.mof") 
#pragma include ("dri/DRI_OperatingSystem.mof") 
#pragma include ("dri/DRI_OperatingSystemCapabilities.mof") 
#pragma include ("dri/DRI_OrderedComponent.mof") 
#pragma include ("dri/DRI_OrderedDependency.mof") 
#pragma include ("dri/DRI_OwningCollectionElement.mof") 
#pragma include ("dri/DRI_PackageInConnector.mof") 
#pragma include ("dri/DRI_PCIController.mof") 
#pragma include ("dri/DRI_PhysicalAssetCapabilities.mof") 
#pragma include ("dri/DRI_PhysicalComponent.mof") 
#pragma include ("dri/DRI_PhysicalConnector.mof") 
#pragma include ("dri/DRI_PhysicalFrame.mof") 
#pragma include ("dri/DRI_PhysicalMemory.mof") 
#pragma include ("dri/DRI_PhysicalMemoryRealizes.mof") 
#pragma include ("dri/DRI_PhysicalPackage.mof") 
#pragma include ("dri/DRI_PortController.mof") 
#pragma include ("dri/DRI_PortImplementsEndpoint.mof") 
#pragma include ("dri/DRI_PowerManagementCapabilities.mof") 
#pragma include ("dri/DRI_PowerManagementService.mof") 
#pragma include ("dri/DRI_PowerSupply.mof") 
#pragma include ("dri/DRI_PowerSupplyRedundancySet.mof") 
#pragma include ("dri/DRI_Privilege.mof") 
#pragma include ("dri/DRI_PrivilegeConcreteDependency.mof") 
#pragma include ("dri/DRI_PrivilegeServiceAffectsElement.mof") 
#pragma include ("dri/DRI_Processor.mof") 
#pragma include ("dri/DRI_ProcessorCapabilities.mof") 
#pragma include ("dri/DRI_ProcessorCore.mof") 
#pragma include ("dri/DRI_ProcessorElementCapabilities.mof") 
#pragma include ("dri/DRI_ProcessorSystemDevice.mof") 
#pragma include ("dri/DRI_ProtocolEndpoint.mof") 
#pragma include ("dri/DRI_Rack.mof") 
#pragma include ("dri/DRI_Realizes.mof") 
#pragma include ("dri/DRI_RealizesExtent.mof") 
#pragma include ("dri/DRI_ReferencedProfile.mof") 
#pragma include ("dri/DRI_RegisteredProfile.mof") 
#pragma include ("dri/DRI_RemoteAccessAvailableToElement.mof") 
#pragma include ("dri/DRI_RemoteServiceAccessPoint.mof") 
#pragma include ("dri/DRI_Role.mof") 
#pragma include ("dri/DRI_RoleBasedAuthorizationService.mof") 
#pragma include ("dri/DRI_RoleBasedManagementCapabilities.mof") 
#pragma include ("dri/DRI_RoleLimitedToTarget.mof") 
#pragma include ("dri/DRI_RoleMemberOfCollection.mof") 
#pragma include ("dri/DRI_RoleOwningCollectionElement.mof") 
#pragma include ("dri/DRI_RoleServiceAffectsElement.mof") 
#pragma include ("dri/DRI_RunningOS.mof") 
#pragma include ("dri/DRI_SAPAvailableForElement.mof") 
#pragma include ("dri/DRI_SAPSAPDependency.mof") 
#pragma include ("dri/DRI_Segfault.mof") 
#pragma include ("dri/DRI_Sensor.mof") 
#pragma include ("dri/DRI_ServiceAccessBySAP.mof") 
#pragma include ("dri/DRI_ServiceAffectsElement.mof") 
#pragma include ("dri/DRI_ServiceAffectsElementWithQuota.mof") 
#pragma include ("dri/DRI_ServiceAvailableToElement.mof") 
#pragma include ("dri/DRI_ServiceServiceDependency.mof") 
#pragma include ("dri/DRI_SettingsDefineCapabilities.mof") 
#pragma include ("dri/DRI_Slot.mof") 
#pragma include ("dri/DRI_SoftwareIdentity.mof") 
#pragma include ("dri/DRI_SoftwareIdentityResource.mof") 
#pragma include ("dri/DRI_SoftwareInstallationService.mof") 
#pragma include ("dri/DRI_SoftwareInstallationServiceCapabilities.mof") 
#pragma include ("dri/DRI_StaticIPAssignmentSettingData.mof") 
#pragma include ("dri/DRI_StorageExtent.mof") 
#pragma include ("dri/DRI_SuppliesPower.mof") 
#pragma include ("dri/DRI_SystemBIOS.mof") 
#pragma include ("dri/DRI_SystemComponent.mof") 
#pragma include ("dri/DRI_SystemDevice.mof") 
#pragma include ("dri/DRI_SystemPackaging.mof") 
#pragma include ("dri/DRI_SystemSpecificCollection.mof") 
#pragma include ("dri/DRI_TCPProtocolEndpoint.mof") 
#pragma include ("dri/DRI_TextRedirectionSAP.mof") 
#pragma include ("dri/DRI_TextRedirectionService.mof") 
#pragma include ("dri/DRI_TextRedirectionTCPProtocolEndpoint.mof") 
#pragma include ("dri/DRI_TimeService.mof") 
#pragma include ("dri/DRI_USBDevice.mof") 
#pragma include ("dri/DRI_USBRedirectionCapabilities.mof") 
#pragma include ("dri/DRI_USBRedirectionSAP.mof") 
#pragma include ("dri/DRI_USBRedirectionService.mof") 
#pragma include ("dri/DRI_USBRedirRemoteServiceAccessPoint.mof") 
#pragma include ("dri/DRI_USBRedirTCPProtocolEndpoint.mof") 
#pragma include ("dri/DRI_UserContact.mof") 
#pragma include ("dri/DRI_UserContactAssignedIdentity.mof") 
