// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_FRU
// ==================================================================
   [Deprecated { "CIM_PhysicalElement", "CIM_ReplacementFRU" }, 
    Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Core::ProductFRU" ), 
    Description ( 
       "The CIM_FRU class is a vendor-defined collection of Products "
       "and/or PhysicalElements that is associated with a Product for "
       "the purpose of supporting, maintaining or upgrading that "
       "Product at the customer\'s location. FRU is an acronym for "
       "\'field replaceable unit\'. \n"
       "The use of FRU has been deprecated in lieu of describing what "
       "is a valid replacement part for a piece of hardware (via the "
       "ElementFRU association from PhysicalElement to ReplacementFRU) "
       "and what has actually been replaced (the ElementHasBeenFRUed "
       "association between PhysicalElements)." )]
class CIM_FRU : CIM_ManagedElement {

      [Deprecated { "CIM_PhysicalElement.PartNumber", 
          "CIM_ReplacementFRU.OrderNumber" }, 
       Key, Description ( "FRU ordering information." ), 
       MaxLen ( 64 ), 
       MappingStrings { "MIF.DMTF|FRU|002.6" }]
   string FRUNumber;

      [Deprecated { "CIM_PhysicalElement.SerialNumber" }, 
       Key, Description ( 
          "FRU identification such as a serial number on software "
          "or a die number on a hardware chip." ), 
       MaxLen ( 64 ), 
       MappingStrings { "MIF.DMTF|FRU|002.7" }]
   string IdentifyingNumber;

      [Deprecated { "CIM_PhysicalElement.Manufacturer", 
          "CIM_ReplacementFRU.Vendor" }, 
       Key, Description ( "The name of the FRU\'s supplier." ), 
       MaxLen ( 256 ), 
       MappingStrings { "MIF.DMTF|FRU|002.4" }]
   string Vendor;

      [Deprecated { "CIM_PhysicalElement.Description", 
          "CIM_ReplacementFRU.Description" }, 
       Override ( "Description" ), 
       Description ( "A textual description of the FRU." ), 
       MappingStrings { "MIF.DMTF|FRU|002.3" }]
   string Description;

      [Deprecated { "CIM_PhysicalElement.Name", 
          "CIM_ReplacementFRU.ElementName" }, 
       Description ( "FRU name." ), 
       MaxLen ( 256 )]
   string Name;

      [Deprecated { "CIM_PhysicalElement.Version" }, 
       Description ( "The FRU\'s revision level." ), 
       MaxLen ( 64 ), 
       MappingStrings { "MIF.DMTF|FRU|002.8" }]
   string RevisionLevel;

      [Deprecated { "CIM_ReplacementFRU.CustomerReplaceable" }, 
       Description ( 
          "Indicates whether the FRU is customer replaceable." )]
   boolean CustomerReplaceable;


};
