// <change cr="CIMCoreCR00919" type="add">new association</change>
//Copyright (c) 2007 DMTF. All rights reserved.
//====================================================================
// CIM_MostCurrentSnapshotInBranch
//====================================================================
   [Association, Experimental, Version ( "2.16.0" ), 
    Description ( 
       "The CIM_MostCurrentSnapshotInBranch association associates an "
       "instance of the CIM_ComputerSystem class representing a "
       "virtual system, and the instance of the "
       "CIM_VirtualSystemSettingData class representing the virtual "
       "system snapshot that is the most current snapshot in a branch "
       "of dependent snapshots. \n"
       "Note that a new branch is implied as a snapshot that is part "
       "of an existing branch is applied to a virtual system, such "
       "that in this case initially that snapshot is the most current "
       "snapshot in that new branch. Note that this association does "
       "not exist if the virtual system was not activated based on a "
       "snapshot or no snapshot was yet created from the current "
       "instance of the virtual system." )]
class CIM_MostCurrentSnapshotInBranch : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 0 ), 
       Max ( 1 ), 
       Description ( 
          "Reference to the instance of the CIM_ComputerSystem "
          "class representing a virtual system." )]
   CIM_ComputerSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Min ( 0 ), 
       Max ( 1 ), 
       Description ( 
          "Reference to the instance of the "
          "CIM_VirtualSystemSettingData class representing the "
          "virtual system snapshot that is the most current "
          "snapshot in a branch of dependent snapshots." )]
   CIM_VirtualSystemSettingData REF Dependent;


};
