// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00722.000" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ManagementSAP
// ==================================================================
   [Association, Experimental, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Service" ), 
    Description ( 
       "Indicates that the associated ServiceAccessPoint provides "
       "management access for the referenced element. For example, it "
       "might be a UDP interface for SNMP access, or it might be a "
       "URL." )]
class CIM_ManagementSAP : CIM_SAPAvailableForElement {

      [Override ( "AvailableSAP" ), 
       Description ( 
          "The access point through which the element can be managed."
           )]
   CIM_ServiceAccessPoint REF AvailableSAP;

      [Override ( "ManagedElement" ), 
       Description ( "The element being managed." )]
   CIM_ManagedElement REF ManagedElement;


};
