// Copyright (c) 2007 DMTF.  All rights reserved.
// <change cr="SVPCCR00026" type ="new">Add class. </change> 
// <change cr="DMTFCR01783" type ="add">change property 
// IndicationsSupported from boolean to uint16. </change>
//===================================================================
// CIM_VirtualSystemManagementCapabilities
//===================================================================
   [Experimental, Version ( "2.15.0" ), 
    UMLPackagePath ( "CIM::Core::Virtualization" ), 
    Description ( 
       "Capabilities of a CIM_VirtualSystemManagementService." )]
class CIM_VirtualSystemManagementCapabilities : CIM_EnabledLogicalElementCapabilities {

      [Description ( 
          "Enumeration of strings each designating a type of "
          "virtual system that the implementation supports. The "
          "types and their string values are implementation "
          "dependent." ), 
       ModelCorrespondence { 
          "CIM_VirtualSystemSettingData.VirtualSystemType" }]
   string VirtualSystemTypesSupported[];

      [Description ( 
          "Enumeration of method identifiers each identifying a "
          "method of class CIM_VirtualSystemManagementService that "
          "is supported synchronously by the implementation." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9" }, 
       Values { "AddResourcesSupported", "DefineSystemSupported", 
          "DestroySystemSupported", 
          "DestroySystemConfigurationSupported", 
          "ModifyResourceSettingsSupported", 
          "ModifySystemSettingsSupported", 
          "RemoveResourcesSupported", 
          "SelectSystemConfigurationSupported", 
          "SnapshotSystemSupported" }]
   uint16 SynchronousMethodsSupported[];

      [Description ( 
          "Enumeration of method identifiers each identifying a "
          "method of class CIM_VirtualSystemManagementService that "
          "is supported asynchronously by the implementation." ), 
       ValueMap { "1", "2", "3", "4", "5", "6", "7", "8", "9" }, 
       Values { "AddResourcesSupported", "DefineSystemSupported", 
          "DestroySystemSupported", 
          "DestroySystemConfigurationSupported", 
          "ModifyResourceSettingsSupported", 
          "ModifySystemSettingsSupported", 
          "RemoveResourcesSupported", 
          "SelectSystemConfigurationSupported", 
          "SnapshotSystemSupported" }]
   uint16 AsynchronousMethodsSupported[];

      [Description ( 
          "Enumeration of indication identifiers each identifying "
          "an indication that is supported by the implementation.\n"
          "VirtualSystemStateChangeIndicationsSupported indicates "
          "whether or not the implementation supports notification "
          "on state changes of CIM_ComputerSystem instances "
          "representing virtual systems.\n"
          "VirtualResourceStateChangeIndicationsSupported indicates "
          "whether or not the implementation supports notification "
          "on state changes of CIM_LogicalDevice instances "
          "representing resources of virtual systems.\n"
          "ConcreteJobStateChangeIndicationsSupported indicates "
          "whether or not the implementation supports notification "
          "on state changes of CIM_ConcreteJob instances." ), 
       ValueMap { "1", "2", "3" }, 
       Values { "VirtualSystemStateChangeIndicationsSupported", 
          "VirtualResourceStateChangeIndicationsSupported", 
          "ConcreteJobStateChangeIndicationsSupported" }]
   uint16 IndicationsSupported[];


};
