// Copyright (c) 2007 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00917" type="new">Added class.</change>
// ==================================================================
//  CIM_MemberOfStatusCollection
// ==================================================================
   [Association, Experimental, Aggregation, Version ( "2.16.0" ), 
    UMLPackagePath ( "CIM::Core::Collection" ), 
    Description ( 
       "CIM_MemberOfStatusCollection is an aggregation used to "
       "establish membership of ManagedElements in a StatusCollection." )]
class CIM_MemberOfStatusCollection : CIM_MemberOfCollection {

      [Key, Aggregate, Override ( "Collection" ), 
       Description ( "The Collection that aggregates members." )]
   CIM_StatusCollection REF Collection;

      [Write, Description ( 
          "The PolicyEnabled property describes whether the "
          "associated Member should be included in the policy "
          "algorithm utilized for the associated "
          "CIM_StatusCollection. At a high level, the policy "
          "algorithm may be represented by an instance of "
          "CIM_PolicyRule associated with the Collection." ), 
       ValueMap { "0", "2", "3", "..", "0x8000.." }, 
       Values { "Unknown", "Include", "Exclude", "DMTF Reserved", 
          "Vendor Reserved" }]
   uint16 PolicyEnabled;


};
