// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="SysDevCR00714.001" type ="change">Update of
// descriptions based on Tech Edit review.</
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ElementHasBeenFRUed
// ==================================================================
   [Association, Experimental, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Physical" ), 
    Description ( 
       "CIM_ElementHasBeenFRUed is an association between two Physical "
       "Elements that indicates that the entity referenced as the "
       "ReplacedElement was swapped for or replaced by the entity "
       "referenced as the ReplacementElement. The association is many "
       "to many, conveying that an element might require several other "
       "elements to replace it, and vice-versa. The typical scenario, "
       "however, is that one PhysicalElement replaces another. It "
       "might not be possible to instrument or manually determine that "
       "an element actually replaced (FRUed) another. This "
       "determination is especially difficult if the original element "
       "is discarded. However, if this information is available, then "
       "this association describes this scenario." )]
class CIM_ElementHasBeenFRUed {

      [Key, Description ( 
          "The PhysicalElement that is being replaced (FRUed)." )]
   CIM_PhysicalElement REF ReplacedElement;

      [Key, Description ( 
          "The element that is used as the replacement part." )]
   CIM_PhysicalElement REF ReplacementElement;


};
