// Copyright (c) 2008 DMTF.  All Rights Reserved.
   [Association, Experimental, Aggregation, Version ( "2.18.0" ), 
    UMLPackagePath ( "CIM::Core::Collection" ), 
    Description ( 
       "CIM_MemberOfPolicyCollection is an aggregation used to "
       "establish membership of ManagedElements in a Collection for "
       "use with policy algorithms. The policy algorithms shall be "
       "specified by either: the semantics of the associated "
       "Collection subclass; or explicitly via association to a "
       "CIM_PolicyRule subclass via CIM_PolicySetAppliesToElement." )]
class CIM_MemberOfPolicyCollection : CIM_MemberOfCollection {

      [Write, Description ( 
          "The Included property describes whether the associated "
          "Member should be included (TRUE) or excluded (FALSE) in "
          "the policy algorithm utilized for the associated "
          "CIM_Collection." )]
   boolean Included = true;


};
