// Copyright (c) 2008 DMTF.  All rights reserved.
   [Experimental, Version ( "2.19.0" ), 
    UMLPackagePath ( "CIM::Core::SettingData" ), 
    Description ( 
       "EnabledLogicalElementSettingData provides the ability to model "
       "a planned or possible configuration of an "
       "EnabledLogicalElement." )]
class CIM_EnabledLogicalElementSettingData : CIM_SettingData {

      [Description ( 
          "RequestedState indicates the desired state for the "
          "element to have if the configuration requested by this "
          "instance of EnabledLogicalElementSettingData is applied "
          "to the EnabledLogicalElement. If this instance of "
          "EnabledLogicalElementSettingData is applied to an "
          "instance of EnabledLogicalElement, the value of the "
          "EnabledLogicalElement.RequestedState property shall be "
          "the value of the "
          "EnabledLogicalElementSettingData.RequestedState "
          "property." ), 
       ValueMap { "2", "3", "4", "6", "7", "8", "9", "10", "11" }, 
       Values { "Enabled", "Disabled", "Shut Down", "Offline", 
          "Test", "Defer", "Quiesce", "Reboot", "Reset" }, 
       ModelCorrespondence { 
          "CIM_EnabledLogicalElement.RequestStateChange", 
          "CIM_EnabledLogicalElement.RequestedState" }]
   uint16 RequestedState;

      [Override ( "ElementName" ), 
       Description ( 
          "The desired ElementName for the EnabledLogicalElement." )]
   string ElementName;


};
