// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01330.001" type ="new">Addition of SoftwareIdentityComponent association</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SoftwareIdentityComponent 
// ==================================================================
   [Association, Experimental, Aggregation, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Software" ), 
    Description ( 
       "SoftwareIdentities can have an arbitrarily complex hierarchy. "
       "SoftwareIdentityComponent is used to construct that hierarchy. "
       "It SHOULD not be used to represent dependency. For example, if "
       "a \'support pack\' represented by a CIM_SoftwareIdentity "
       "consist of multiple installable software packages then this "
       "association class enables a management client to determine all "
       "the SoftwareIdentities that are be contained in the support "
       "pack." )]
class CIM_SoftwareIdentityComponent : CIM_Component {

      [Override ( "GroupComponent" ), 
       Description ( 
          "The container SoftwareIdentity in the association." )]
   CIM_SoftwareIdentity REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The contained SoftwareIdentity in the association." )]
   CIM_SoftwareIdentity REF PartComponent;


};
