// Copyright (c) 2006 DMTF.  All rights reserved.
// <change cr="CIMCore00807" type ="change">Remove
// MaxQualifier on ElementCapabilities.ManagedElement.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="SVPCCR00039" type="add">Add property
// Characteristics.</change>
// ==================================================================
//  CIM_ElementCapabilities 
// ==================================================================
   [Association, Version ( "2.14.0" ), 
    UMLPackagePath ( "CIM::Core::Capabilities" ), 
    Description ( 
       "ElementCapabilities represents the association between "
       "ManagedElements and their Capabilities. Note that the "
       "cardinality of the ManagedElement reference is Min(1). This "
       "cardinality mandates the instantiation of the "
       "ElementCapabilities association for the referenced instance of "
       "Capabilities. ElementCapabilities describes the existence "
       "requirements and context for the referenced instance of "
       "ManagedElement. Specifically, the ManagedElement MUST exist "
       "and provides the context for the Capabilities." )]
class CIM_ElementCapabilities {

      [Key, Min ( 1 ), 
       Description ( "The managed element." )]
   CIM_ManagedElement REF ManagedElement;

      [Key, Description ( 
          "The Capabilities object associated with the element." )]
   CIM_Capabilities REF Capabilities;

      [Experimental, Description ( 
          "Characteristics provides descriptive information about "
          "the Capabilities. when the value 2 \"Default\" is "
          "specified, the associated Capabilities shall represent "
          "the default capabilities of the associated Managed "
          "Element \n"
          "when the value 2 \"Default\" is not specified, the "
          "Capabilities instance may represent the default "
          "capabilities of the Managed Element\n"
          "When the value 3 \"Current\" is specified, the "
          "associated Capabilities shall represent the current "
          "capabilities of the associated Managed Element\n"
          "When the value 3 \"Current\" is not specified, the "
          "Capabilities instance may represent the current "
          "capabilities of the Managed Element." ), 
       ValueMap { "2", "3", "..", "32768..65535" }, 
       Values { "Default", "Current", "DMTF Reserved", 
          "Vendor Specific" }]
   uint16 Characteristics[];


};
