// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00827" type="new">Add class.</change>
// ==================================================================
//  CIM_ProductElementComponent
// ==================================================================
   [Association, Experimental, Aggregation, Composition, Version ( 
       "2.15.0" ), 
    UMLPackagePath ( "CIM::Core::ProductFRU" ), 
    Description ( 
       "Indicates that the referenced ManagedElement is part of a Product."
        )]
class CIM_ProductElementComponent : CIM_Component {

      [Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( "The Product." )]
   CIM_Product REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The ManagedElement which is a part of the Product." )]
   CIM_ManagedElement REF PartComponent;


};
