// Copyright (c) 2007 DMTF.  All rights reserved.
// <change cr="SVPCCR00026" type ="new">Add class. </change> 
// ===================================================================
//  CIM_AggregatedVirtualSystemManagementService
// ===================================================================
   [Association, Experimental, Version ( "2.15.0" ), 
    UMLPackagePath ( "CIM::Core::Virtualization" ), 
    Description ( 
       "The association between an instance of CIM_ComputerSystem "
       "representing a central management system (like a hardware "
       "management console or a blade center management console), and "
       "an instance of CIM_VirtualSystemManagementService representing "
       "virtualization management services for one of the systems "
       "controlled by the central management system." )]
class CIM_AggregatedVirtualSystemManagementService : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "Reference to an instance of CIM_ComputerSystem "
          "representing a central management system." )]
   CIM_ComputerSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "Reference to the instance of "
          "CIM_VirtualSystemManagementService representing the "
          "virtual system management services available at one of "
          "the systems controlled by the system referenced by "
          "Antecedent." )]
   CIM_VirtualSystemManagementService REF Dependent;


};
