// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ReplaceableProductFRU
// ==================================================================
   [Association, Deprecated { "CIM_ElementFRU" }, 
    Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Core::ProductFRU" ), 
    Description ( 
       "ReplaceableProductFRU is an association between Product and "
       "FRU that shows what Product components may be replaced. The "
       "association is one to many, conveying that a Product can have "
       "many FRUs, and that a particular instance of a FRU is only "
       "applied to one (instance of a) Product. \n"
       "The use of this association has been deprecated since the "
       "concept of FRUing really applies to hardware "
       "(PhysicalElements) and not to Products, and the granularity of "
       "a Product may be insufficient. Now, the replacement FRU "
       "information is included in CIM_ReplacementFRU, and tied to the "
       "PhysicalElement via the association, ElementFRU." )]
class CIM_ReplaceableProductFRU {

      [Deprecated { "CIM_ElementFRU.ReplaceableElement" }, 
       Key, Max ( 1 ), 
       Description ( "The Product to which the FRU is applied." )]
   CIM_Product REF Product;

      [Deprecated { "CIM_ElementFRU.ReplacementElement" }, 
       Key, Description ( "The FRU." )]
   CIM_FRU REF FRU;


};
