// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NATService
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::NAT" ), 
    Description ( 
       "NATService describes that address translation is being "
       "performed by the hosting system. NAT stands for Network "
       "Address Translation and allows an organization\'s network to "
       "appear from the outside to use a different address space than "
       "what it really is using. The specific parameters of the "
       "translation(s) are defined as NATSettingData, and associated "
       "with this service using the ElementSettingData relationship." )]
class CIM_NATService : CIM_ForwardingService {


};
