// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_TCPEndpointStatistics
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::ChannelExtender" ), 
    Description ( 
       "TCPEndpointStatistics is the statistics for the TCP Protocol "
       "Endpoint." )]
class CIM_TCPEndpointStatistics : CIM_ProtocolEndpointStatistics {

      [Description ( 
          "The total number of segments received in error (e.g., "
          "bad TCP checksums)." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpInErrs" }]
   uint32 ReceivedSegmentsInError;

      [Description ( 
          "The number of TCP segments sent containing the RST flag." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpOutRsts" }]
   uint32 SentResetSegments;


};
