// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_LACPPortStatistics
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::8023LAG" ), 
    Description ( 
       "Statistics for Link Aggregation Control Protocol (LACP). These "
       "statistics are for each LAGPort8023ad where LACP is enabled in "
       "a device." )]
class CIM_LACPPortStatistics : CIM_StatisticalData {

      [Description ( 
          "The number of valid LACPDUs received on this Aggregation Port."
           ), 
       Counter, MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortStatsLACPDUsRx" }]
   uint32 PortStatsLACPDUsRx;

      [Description ( 
          "The number of valid Marker PDUs received on this Aggregation Port."
           ), 
       Counter, MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortStatsMarkerPDUsRx" }]
   uint32 PortStatsMarkerPDUsRx;

      [Description ( 
          "The number of valid Marker Response PDUs received on "
          "this Aggregation Port." ), 
       Counter, MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortStatsMarkerResponsePDUsRx" }]
   uint32 PortStatsMarkerResponsePDUsRx;

      [Description ( 
          "The number of frames received that either: \n"
          "* carry the Slow Protocols Ethernet Type value (43B.4), "
          "but contain an unknown PDU, or: \n"
          "* are addressed to the Slow Protocols group MAC Address "
          "(43B.3), but do not carry the Slow Protocols Ethernet "
          "Type." ), 
       Counter, MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortStatsUnknownRx" }]
   uint32 PortStatsUnknownRx;

      [Description ( 
          "The number of frames received that carry the Slow "
          "Protocols Ethernet Type value (43B.4), but contain a "
          "badly formed PDU or an illegal value of Protocol Subtype "
          "(43B.4)." ), 
       Counter, MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortStatsIllegalRx" }]
   uint32 PortStatsIllegalRx;

      [Description ( 
          "The number of LACPDUs transmitted on this Aggregation Port."
           ), 
       Counter, MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortStatsLACPDUsTx" }]
   uint32 PortStatsLACPDUsTx;

      [Description ( 
          "The number of Marker PDUs transmitted on thisAggregation Port."
           ), 
       Counter, MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortStatsMarkerPDUsTx" }]
   uint32 PortStatsMarkerPDUsTx;

      [Description ( 
          "The number of Marker Response PDUs transmitted on this "
          "Aggregation Port." ), 
       Counter, MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortStatsMarkerResponsePDUsTx" }]
   uint32 PortStatsMarkerResponsePDUsTx;


};
