// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSTunnelHop
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "A destination in an MPLS tunnel. This may be specified by the "
       "user, calculated for the tunnel or actually in use. These "
       "different aspects are indicated by the HopDerivation "
       "enumeration." )]
class CIM_MPLSTunnelHop : CIM_RemoteServiceAccessPoint {

      [Description ( "The method used to determine the destination." ), 
       ValueMap { "0", "2", "3" }, 
       Values { "Unknown", "User", "Calculated" }]
   uint16 HopDerivation;


};
