// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_TranslationPoolForNAT
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::NAT" ), 
    Description ( 
       "TranslationPoolForNAT associates a pool/range of addresses "
       "available as the result of a translation, with the specific "
       "translation that uses this pool." )]
class CIM_TranslationPoolForNAT : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The pool/range of addresses available for translation." )]
   CIM_RangeOfIPAddresses REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The specific translation that uses the pool of addresses." )]
   CIM_NATListBasedSettings REF Dependent;


};
