// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSCapabilities
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "This class specifies the capabilities of an MPLSService or "
       "MPLSProtocolEndpoint (interface) on a Label Switched Router "
       "(LSR). The association CIM_ElementCapabilities relates the "
       "instance with its MPLS Service and/or Endpoint." )]
class CIM_MPLSCapabilities : CIM_Capabilities {

      [Description ( 
          "This is the minimum value of an MPLS label that this "
          "Endpoint or MPLSService is willing to receive. The "
          "values of an MPLSProtocolEndpoint may overrule the "
          "values specified for the LSR as a whole, based on the "
          "Endpoint\'s boolean property OverruleLSR." ), 
       MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInterfaceLabelMinIn" }]
   uint32 LabelMinIn;

      [Description ( 
          "This is the maximum value of an MPLS label that this "
          "Endpoint or MPLSService is willing to receive. The "
          "values of an MPLSProtocolEndpoint may overrule the "
          "values specified for the LSR as a whole, based on the "
          "Endpoint\'s boolean property OverruleLSR." ), 
       MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInterfaceLabelMaxIn" }]
   uint32 LabelMaxIn;

      [Description ( 
          "This is the minimum value of an MPLS label that this "
          "Endpoint or MPLSService is willing to send. The values "
          "of an MPLSProtocolEndpoint may overrule the values "
          "specified for the LSR as a whole, based on the "
          "Endpoint\'s boolean property OverruleLSR." ), 
       MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInterfaceLabelMinOut" }]
   uint32 LabelMinOut;

      [Description ( 
          "This is the maximum value of an MPLS label that this "
          "Endpoint or MPLSService is willing to send. The values "
          "of an MPLSProtocolEndpoint may overrule the values "
          "specified for the LSR as a whole, based on the "
          "Endpoint\'s boolean property OverruleLSR." ), 
       MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInterfaceLabelMaxOut" }]
   uint32 LabelMaxOut;


};
