// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSCrossConnect
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "This class specifies information for switching between "
       "Segments within a LSR. It is scoped by a Computer System, that "
       "is the Label Switched Router, via the HostedService "
       "association. Specific In/Out Segments are associated with the "
       "cross-connect using the relationship, MPLSSegmentInXC. The "
       "service can support point-to-point, point-to-multipoint and "
       "multipoint-to-point connections by defining multiple instances "
       "of the association. CrossConnect Services can be aggregated "
       "into an overarching MPLSService using the CIM_ServiceComponent "
       "association. And, the LSP to which the CrossConnect belongs is "
       "indicated by the association, CrossConnectLSP." )]
class CIM_MPLSCrossConnect : CIM_Service {

      [Description ( 
          "Denotes whether or not this CrossConnect entry and "
          "associated In and Out Segments should be restored "
          "automatically after failures." ), 
       MappingStrings { "MIB.IETF|MPLS-LSR-MIB.MPLSXCIsPersistent" }]
   boolean IsPersistent;

      [Description ( 
          "Identifies a stack of labels to be pushed beneath the "
          "top label. Note that the top label identified in an "
          "instance of OutSegment ensures that all the components "
          "of a multipoint-to-point connection have the same "
          "outgoing label. This array is \'Ordered\' to maintain "
          "the sequence of entries." ), 
       ArrayType ( "Ordered" )]
   uint16 LabelStack[];


};
