// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSFecOfTunnel
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "This association defines the forwarding equivalency class "
       "(FEC) for a traffic engineering tunnel. It is typically just "
       "an IP destination address - and can be defined using a "
       "FilterList. Although this is not truly a filter on the tunnel, "
       "the FilterList class is reused to describe the traffic on the "
       "tunnel." )]
class CIM_MPLSFecOfTunnel : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "The FilterList defining the FEC of the MPLSTunnel." )]
   CIM_FilterList REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The MPLSTunnel." )]
   CIM_MPLSTunnel REF Dependent;


};
