// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_TCPSettings
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::ChannelExtender" ), 
    Description ( 
       "TCPSettings defines settings for a single TCPProtocolEndpoint "
       "or a group of TCPProtocolEndpoints which belongs to the "
       "transport layer of the ComputerSystem or more granular to the "
       "TCP NetworkPipe. TCPSettings class defines the attributes that "
       "affect the behavior of TCPProtocolEndpoint(s). The attributes "
       "are tied to the TCPProtocolEndpoint(s) though an "
       "ElementSettingData association." )]
class CIM_TCPSettings : CIM_SettingData {

      [Description ( 
          "The Algorithm used to determine the timeout value used "
          "for retransmitting unacknowledged octets. (1) Other - "
          "none of the following (2) constant - a constant rto (3) "
          "rsre - MIL-STD-1778, Appendix B (4) vanj - Van "
          "Jacobson\'s Algorithm." ), 
       ValueMap { "1", "2", "3", "4" }, 
       Values { "Other", "Constant", "Rsre", "Vanj" }, 
       MappingStrings { "MIB.IETF|TCP-MIB.tcpRtoAlgorithm" }]
   uint16 RetransmissionTimeoutAlgorithm;

      [Description ( 
          "The minimum value permitted by a TCP implementation for "
          "the retransmission timeout, measured in milliseconds. "
          "More refined semantics for objects of this type depend "
          "upon the algorithm used to determine the retransmission "
          "timeout. In particular, when the timeout algorithm is "
          "rsre (3), an object of this type has the semantics of "
          "the LBOUND quantity described in RFC 793." ), 
       Units ( "MilliSeconds" ), 
       MappingStrings { "MIB.IETF|TCP-MIB.tcpRtoMin" }, 
       PUnit ( "second * 10^-3" )]
   uint16 RetransmissionTimeoutMin;

      [Description ( 
          "The maximum value permitted by a TCP implementation for "
          "the retransmission timeout, measured in milliseconds. "
          "More refined semantics for objects of this type depend "
          "upon the algorithm used to determine the retransmission "
          "timeout. In particular, when the timeout algorithm is "
          "rsre (3), an object of this type has the semantics of "
          "the UBOUND quantity described in RFC 793." ), 
       Units ( "MilliSeconds" ), 
       MappingStrings { "MIB.IETF|TCP-MIB.tcpRtoMax" }, 
       PUnit ( "second * 10^-3" )]
   uint16 RetransmissionTimeoutMax;


};
