// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_RelatedTopologyGraph
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::Topology" ), 
    Description ( 
       "RelatedTopologyGraph associates a TopologyGraph instance with "
       "a ConnectivityCollection. This relationship is different from "
       "a topology graph collecting ConnectivityCollections. It "
       "describes the embedding of a lower layer topology within a "
       "ConnectivityCollection. For example, a layer 3 IP subnet "
       "(represented by an instance of IPConnectivitySubnet) collects "
       "a set of IPProtocolEndpoints. It might also be associated with "
       "a TopologyGraph describing the layer 2 switched Ethernet "
       "topology over which the IP subnet runs. This association of "
       "Layer 3 to Layer 2 is described as a Dependency relationship, "
       "where the Layer 3 connectivity is dependent on the Layer 2 "
       "topology." )]
class CIM_RelatedTopologyGraph : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "A topology graph which underlies a ConnectivityCollection."
           )]
   CIM_TopologyGraph REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The ConnectivityCollection which depends on the "
          "underlying topology." )]
   CIM_ConnectivityCollection REF Dependent;


};
