// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_IPSettings
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::ChannelExtender" ), 
    Description ( 
       "IPSettings class defines the attributes that affect the "
       "behavior of an IPProtocolEndpoint. The attributes are tied to "
       "the IPProtocolEndpoint though an ElementSettingData "
       "association. This class may also be used to specify the "
       "default settings for all IPProtocolEndpoint instances created "
       "on a ComputerSystem though an ElementSettingData association "
       "to the ComputerSystem. Processes that create new instances of "
       "IPProtocolEndpoint and the associated setting data should "
       "check for a IPSettings instance associated with the "
       "ComputerSystem and should only create a new instance of "
       "IPSettings specific to the IPProtocolEndpoint if the default "
       "settings need to be overridden for the specific "
       "IPProtocolEndpoint instance." )]
class CIM_IPSettings : CIM_SettingData {

      [Write, Description ( 
          "Time in seconds to keep an IP fragment in memory." ), 
       Units ( "Seconds" ), 
       MappingStrings { "MIB.IETF|IP-MIB.ipReasmTimeout" }, 
       PUnit ( "second" )]
   uint32 FragmentationTimeout;

      [Write, Description ( 
          "Set the default time-to-live value of outgoing packets." ), 
       Units ( "Seconds" ), 
       MinValue ( 1 ), 
       MaxValue ( 255 ), 
       MappingStrings { "MIB.IETF|IP-MIB.ipDefaultTTL" }, 
       PUnit ( "second" )]
   uint32 DefaultTimeToLive;

      [Write, Description ( "This property enables IP forwarding." ), 
       MappingStrings { "MIB.IETF|IP-MIB.ipForwarding" }]
   boolean EnableIPForwarding;


};
