// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_HostedMPLSTunnelHop
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "HostedMPLSTunnelHop defines a MPLSTunnelHop in the context of "
       "a scoping AutonomousSystem. It represents a MPLSTunnelHop that "
       "only has meaning in the context of an AutonomousSystem." )]
class CIM_HostedMPLSTunnelHop : CIM_HostedDependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( "The scoping system." )]
   CIM_AutonomousSystem REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The collection defined in the context of a system." )]
   CIM_MPLSTunnelHop REF Dependent;


};
