// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NATSettingData
// ==================================================================
   [Experimental, Abstract, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::NAT" ), 
    Description ( 
       "NATSettingData is an abstract class specifying the general "
       "parameters of an address translation. This data is specific to "
       "the system on which the NATService is running. The scoping "
       "system is described using the inherited ScopedSetting "
       "association." )]
class CIM_NATSettingData : CIM_ScopedSettingData {

      [Description ( 
          "Indicates whether the translation is of internal "
          "addresses for external visibility (TRUE) or external "
          "addresses for internal use (FALSE)." )]
   boolean IsInside;

      [Description ( 
          "Indicates whether the addresses to be translated are "
          "based on examining source addressing (2), destination "
          "addressing (3) or both (4). The latter is referred to as "
          "\'Policy NAT\'." ), 
       ValueMap { "2", "3", "4" }, 
       Values { "Source", "Destination", 
          "Both Source and Destination" }]
   uint16 AddressExamined;


};
