// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NATListBasedSettings
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::NAT" ), 
    Description ( 
       "NATListBasedSettings extends the general NATSettingData class "
       "to describe that the address translation is dynamically chosen "
       "from a list, and translated using a pool of possible "
       "addresses. A parameter indicates whether the addresses "
       "(translated to) can be reused (aka, overloaded). This is also "
       "referred to as PAT - port address translation, since the "
       "overloading relies on TCP and UDP port values to disambiguate "
       "connections. \n"
       "\n"
       "Via a mandatory association to a FilterList, the addresses to "
       "be translated are described. Via another mandatory "
       "association, TranslationPoolForNAT, the information regarding "
       "the resulting/translated addresses are defined." )]
class CIM_NATListBasedSettings : CIM_NATSettingData {

      [Description ( 
          "Indicates whether the address(es) that are translated to "
          "(the global, external addresses), may be used by more "
          "than one local address needing translation. The "
          "translation MUST be defined as \'inside\' (IsInside= "
          "TRUE) for this property to be valid." ), 
       ModelCorrespondence { "CIM_NATSettingData.IsInside" }]
   boolean OverloadingPermitted;


};
