// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_MPLSCRLSPTrfcProf
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "Class to represent the Constraint-based Routed LSP (CR-LSP) "
       "traffic parameters as specified in [RFC3212]." )]
class CIM_MPLSCRLSPTrfcProf : CIM_MPLSQosPRTrfcProf {

      [Description ( 
          "Property to indicate at what granularity the CDR "
          "(allocated to the CR-LSP) is made available." ), 
       ValueMap { "0", "1", "2" }, 
       Values { "Unspecified", "Frequently", "Very Frequently" }]
   uint16 CRLSPFrequency;

      [Description ( 
          "Property to indicate the CR-LSP\'s relative share (in "
          "percent) of the possible excess bandwidth above its "
          "committed rate." ), 
       Units ( "Percent" ), 
       MinValue ( 0 ), 
       MaxValue ( 100 ), 
       PUnit ( "percent" )]
   uint8 CRLSPWeight;

      [Description ( 
          "Property to indicate the CR-LSP\'s committed data rate "
          "in bytes per second." ), 
       Units ( "Bytes per Second" ), 
       PUnit ( "byte / second" )]
   uint16 CRLSPCommitedDataRate;

      [Description ( 
          "Property to indicate the CR-LSP\'s committed burst size in bytes."
           ), 
       Units ( "Bytes" ), 
       PUnit ( "byte" )]
   uint16 CRLSPCommitedBurstSize;


};
