// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_TCPStatisticalData
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::ChannelExtender" ), 
    Description ( 
       "TCPStatisticalData is the statistics class for a TCP "
       "connection group which belongs to the transport layer of the "
       "ComputerSystem or more granular to TCP NetworkPipe." )]
class CIM_TCPStatisticalData : CIM_StatisticalData {

      [Description ( 
          "The number of times TCP connections have made a direct "
          "transition to the SYN_SENT state from the CLOSED state." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpActiveOpens" }]
   uint32 ActiveOpenConnections;

      [Description ( 
          "The number of times TCP connections have made a direct "
          "transition to the SYN_RCVD state from the LISTEN state." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpPassiveOpens" }]
   uint32 PassiveOpenConnections;

      [Description ( 
          "The number of times TCP connections have made a direct "
          "transition to the CLOSED state from either the SYN_SENT "
          "state or the SYN_RCVD state, plus the number of times "
          "TCP connections have made a direct transition to the "
          "LISTEN state from the SYN_RCVD state." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpAttemptFails" }]
   uint32 AttemptsFails;

      [Description ( 
          "The number of times TCP connections have made a direct "
          "transition to the CLOSED state from either the "
          "ESTABLISHED state or the CLOSE_WAIT state." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpEstabResets" }]
   uint32 EstablishedResets;

      [Description ( 
          "The number of TCP connections for which the current "
          "state is either ESTABLISHED or CLOSE_ WAIT." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpCurrEstab" }]
   uint32 EstablishedConnections;

      [Description ( 
          "The total number of segments received in error (e.g., "
          "bad TCP checksums)." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpInSegs" }]
   uint32 ReceivedSegments;

      [Description ( 
          "The total number of segments sent, including those on "
          "current connections but excluding those containing only "
          "retransmitted octets." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpOutSegs" }]
   uint32 SentSegments;

      [Description ( 
          "The total number of segments retransmitted - that is, "
          "the number of TCP segments transmitted containing one or "
          "more previously transmitted octets." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpRetransSegs" }]
   uint32 RetransmittedSegments;

      [Description ( 
          "The total number of segments received in error (e.g., "
          "bad TCP checksums)." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpInErrs" }]
   uint32 ReceivedSegmentsInError;

      [Description ( 
          "The number of TCP segments sent containing the RST flag." ), 
       Counter, MappingStrings { "MIB.IETF|TCP-MIB.tcpOutRsts" }]
   uint32 SentResetSegments;


};
