// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ProtocolEndpointStatistics
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::ChannelExtender" ), 
    Description ( 
       "ProtocolEndpointStatistics is the statistics class for the "
       "Protocol Endpoint." )]
class CIM_ProtocolEndpointStatistics : CIM_StatisticalData {

      [Description ( 
          "The total number of input PDUs (Protocol Data Unit) "
          "received from interfaces, including those received in "
          "error." ), 
       Counter]
   uint32 ReceivedPDUs;

      [Description ( 
          "The number of input PDUs (Protocol Data Unit) discarded "
          "due to errors in their headers." ), 
       Counter]
   uint32 ReceivedPDUHeaderErrors;

      [Description ( 
          "The number of input PDUs (Protocol Data Unit) discarded "
          "because the address in their header was not a valid "
          "address to be received at this entity." ), 
       Counter]
   uint32 ReceivedPDUAddressErrors;

      [Description ( 
          "The total number of PDUs (Protocol Data Unit) sent to "
          "interfaces for transmission." ), 
       Counter]
   uint32 SentPDUs;


};
