// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSHopInTunnel
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "This association represents the relationship between the "
       "tunnel head-end and the first hop in the tunnel\'s path. The "
       "hop may be of type Specified, Computed, or Actual." )]
class CIM_MPLSHopInTunnel : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The head-end of an MPLS traffic engineering tunnel." )]
   CIM_MPLSTunnelHop REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The MPLSTunnel whose first hop is described." )]
   CIM_MPLSTunnel REF Dependent;


};
