// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSSegmentInXC
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "Defines the association between an In or Out Segment and a "
       "CrossConnect Service. The Segment is dependent on the Cross "
       "Connect for switching within the LSR." )]
class CIM_MPLSSegmentInXC : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The MPLSCrossConnect." )]
   CIM_MPLSCrossConnect REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "An MPLSSegment dependent on the CrossConnect for switching."
           )]
   CIM_MPLSSegment REF Dependent;


};
