// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSEndpointBuffers
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::Buffers" ), 
    Description ( 
       "This association indicates the buffer resources explicitly "
       "supporting an MPLS interface." )]
class CIM_MPLSEndpointBuffers : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The MPLSBuffer supporting the MPLS interface." )]
   CIM_MPLSBuffers REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The MPLSProtocolEndpoint dependent on the buffer." )]
   CIM_MPLSProtocolEndpoint REF Dependent;


};
