// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSSegmentStats
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "The class represents the statistics for an In or Out "
       "MPLSSegment. The statistics are associated to the Segment "
       "using the relationship CIM_ElementStatisticalData." )]
class CIM_MPLSSegmentStats : CIM_StatisticalData {

      [Description ( 
          "This value represents the total number of octets "
          "received/sent by this Segment. Whether it denotes In or "
          "Out Segments depends on the instance associated with "
          "MPLSSegmentStats." ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInSegmentOctets", 
          "MIB.IETF|MPLS-LSR-MIB.MPLSIOutSegmentOctets" }]
   uint32 NumberOfOctets;

      [Description ( 
          "Total number of packets received/sent by this Segment. "
          "Whether this value denotes In or Out Segments depends on "
          "the instance associated with MPLSSegmentStats." ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInSegmentPackets", 
          "MIB.IETF|MPLS-LSR-MIB.MPLSOutSegmentPackets" }]
   uint32 NumberOfPackets;

      [Description ( 
          "The number of errored packets received/sent on this "
          "Segment. Whether this value denotes In or Out Segments "
          "depends on the instance associated with "
          "MPLSSegmentStats." ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInSegmentErrors", 
          "MIB.IETF|MPLS-LSR-MIB.MPLSIOutSegmentErrors" }]
   uint32 NumberOfErrors;

      [Description ( 
          "The number of labeled packets received/sent on this "
          "Segment, which were chosen to be discarded even though "
          "no errors had been detected to prevent their being "
          "transmitted. One possible reason for discarding such a "
          "labeled packet could be to free up buffer space. Whether "
          "this value denotes In or Out Segments depends on the "
          "instance associated with MPLSSegmentStats." ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInSegmentDiscards", 
          "MIB.IETF|MPLS-LSR-MIB.MPLSIOutSegmentDiscards" }]
   uint32 NumberOfDiscards;


};
