// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="NetworksCR00044" type ="change">
// Rename class from VLANSwitchSettings to VLANSystemSettingData.
// change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_VLANSystemSettingData
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::VLAN" ), 
    Description ( 
       "The VLAN configuration data for a system. It is associated to "
       "the System to which it applies using the ElementSettingData "
       "association." )]
class CIM_VLANSystemSettingData : CIM_SettingData {

      [Description ( 
          "List of VLANs which are reserved for pre-determined "
          "uses/media types, etc. An example of this is reservation "
          "of VLANs specifically for use with FDDI or Token Ring." )]
   uint16 ReservedVLANList[];

      [Description ( 
          "This is a set of VLANs reserved for use internally by the switch."
           )]
   uint16 InternalVLANList[];

      [Description ( 
          "The current number of VLANs configured in the switch." )]
   uint16 NumberOfConfiguredVLANs;

      [Description ( 
          "List of VLANs dynamically created in the switch." )]
   uint16 DynamicVLANList[];

      [Description ( 
          "List of VLANs statically created in the switch." )]
   uint16 StaticVLANList[];


};
