// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_MPLSPerformance
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "This class contains performance information for MPLS entities "
       "such as an MPLS Endpoint or LSP Tunnel. The statistics are "
       "associated with the MPSL entity, using the general "
       "CIM_ElementStatisticalData relationship." )]
class CIM_MPLSPerformance : CIM_StatisticalData {

      [Description ( "Denotes the number of packets lost." ), 
       Counter]
   uint32 NumberOfPacketsLost;

      [Description ( 
          "Denotes the number of packets successfully transmitted." ), 
       Counter]
   uint32 NumberOfPacketsTransmitted;

      [Description ( "Denotes the number of octets transmitted." ), 
       Counter]
   uint32 NumberOfOctets;

      [Description ( 
          "Denotes the average delay of the packets transmitted in "
          "milliseconds." ), 
       Units ( "MilliSeconds" ), 
       Gauge, PUnit ( "second * 10^-3" )]
   uint16 Delay;

      [Description ( 
          "Denotes availability in hundredths of a percent." ), 
       Units ( "Hundredths of Percent" ), 
       MinValue ( 0 ), 
       MaxValue ( 100000 ), 
       PUnit ( "percent * 10^-2" )]
   uint16 Availability;


};
