// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSFilterAtXC
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "The association denotes a filter list defining what traffic is "
       "mapped into the CrossConnect Service. A filter list is "
       "associated with the CrossConnect at the originating LSR." )]
class CIM_MPLSFilterAtXC : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "A FilterList defining what traffic is mapped into the "
          "CrossConnect Service." )]
   CIM_FilterList REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The CrossConnect whose traffic is filtered." )]
   CIM_MPLSCrossConnect REF Dependent;


};
