// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSSegmentOnProtocolEP
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "An MPLSSegment is defined in the context of an MPLS Endpoint. "
       "This association makes that relationship explicit." )]
class CIM_MPLSSegmentOnProtocolEP : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The MPLSProtocolEndpoint which scopes the Segment." )]
   CIM_MPLSProtocolEndpoint REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "An MPLSSegment on the ProtocolEndpoint." )]
   CIM_MPLSSegment REF Dependent;


};
