// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_VLANMembershipSettingData
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::VLAN" ), 
    Description ( 
       "For dynamic VLAN assignment, these rules define how incoming "
       "traffic is assigned to a VLAN. A typical set of assignment "
       "rules include assignment based on MAC address, IP address, or "
       "IP subnet. Many other criteria or combination of criteria may "
       "be used." )]
class CIM_VLANMembershipSettingData : CIM_ConnectivityMembershipSettingData {


};
