// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_DeviceConnectivityCollection
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::Topology" ), 
    Description ( 
       "DeviceConnectivityCollection describes connectivity WITHIN a "
       "single system. The system forwards packets among the members "
       "of the collection. For example, this class is used to "
       "represent connectivity within a router or switch. There may be "
       "multiple DeviceConnectivityCollection instances for a system, "
       "when multiple forwarding domains exist. For example, an "
       "Ethernet switch may separate its LANEndpoints into two groups, "
       "each associated with a different virtual LAN. The LANEndpoints "
       "for each group would be segregated into separate "
       "DeviceConnectivity Collections." )]
class CIM_DeviceConnectivityCollection : CIM_ConnectivityCollection {


};
