// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_LAGPortPartnerSettings
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::8023LAG" ), 
    Description ( 
       "LAGPortPartnerSettings contains the configuration information "
       "for a protocol Partner of a LAG port. This allows manually "
       "configured aggregation. The configuration information is "
       "associated with an instance of LAGPort8023ad via "
       "ElementSettingData." )]
class CIM_LAGPortPartnerSettings : CIM_SettingData {

      [Write, Description ( 
          "A 6-octet MACAddress value representing the "
          "administrative value of the Aggregation Port\'s protocol "
          "Partner\'s System ID. The assigned value is used, along "
          "with the values of the other properties of this class, "
          "in order to achieve manually configured aggregation. For "
          "more information, refer to the IEEE 802.3 document, "
          "Subclause 30.7.2.1.8. Note that the MAC address is "
          "formatted as twelve hexadecimal digits (e.g., "
          "\"010203040506\"), with each pair representing one of "
          "the six octets of the MAC address in \"canonical\" bit "
          "order according to RFC 2469." ), 
       MaxLen ( 12 ), 
       MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortPartnerAdminSystemID" }, 
       ModelCorrespondence { 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminSystemPriority", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminKey", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminPort", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminPortPriority", 
          "CIM_LAGPortPartnerConnection.PortPartnerOperSystemID" }]
   string PortPartnerAdminSystemID;

      [Write, Description ( 
          "A 2-octet value used to define the administrative value "
          "of priority associated with the Partner\'s System ID. "
          "The assigned value is used, along with the values of the "
          "other properties of this class, in order to achieve "
          "manually configured aggregation. For more information, "
          "refer to the IEEE 802.3 document, Subclause 30.7.2.1.6." ), 
       MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortPartnerAdminSystemPriority" }, 
       ModelCorrespondence { 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminSystemID", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminKey", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminPort", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminPortPriority", 
          "CIM_LAGPortPartnerConnection.PortPartnerOperSystemPriority" }]
   uint16 PortPartnerAdminSystemPriority;

      [Write, Description ( 
          "The current administrative value of the 16-bit Key for "
          "the protocol Partner. The assigned value is used, along "
          "with the values of the other properties of this class, "
          "in order to achieve manually configured aggregation. For "
          "more information, refer to the IEEE 802.3 document, "
          "Subclause 30.7.2.1.10." ), 
       MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortPartnerAdminKey" }, 
       ModelCorrespondence { 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminSystemID", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminSystemPriority", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminPort", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminPortPriority", 
          "CIM_LAGPortPartnerConnection.PortPartnerOperKey" }]
   uint16 PortPartnerAdminKey;

      [Write, Description ( 
          "The current administrative value of the port number for "
          "the protocol Partner. This is a 16-bit value. The "
          "assigned value is used, along with the values of the "
          "other properties of this class, in order to achieve "
          "manually configured aggregation. For more information, "
          "refer to the IEEE 802.3 document, Subclause 30.7.2.1.16." ), 
       MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortPartnerAdminPort" }, 
       ModelCorrespondence { 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminSystemID", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminSystemPriority", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminKey", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminPortPriority", 
          "CIM_LAGPortPartnerConnection.PortPartnerOperPort" }]
   uint16 PortPartnerAdminPort;

      [Write, Description ( 
          "The current administrative value of the port priority "
          "for the protocol Partner. This is a 16-bit value. The "
          "assigned value is used, along with the values of the "
          "other properties of this class, in order to achieve "
          "manually configured aggregation. For more information, "
          "refer to the IEEE 802.3 document, Subclause 30.7.2.1.18." ), 
       MappingStrings { 
          "MIB.IEEE|IEEE8023-LAG-MIB.dot3adAggPortPartnerAdminPortPriority" }, 
       ModelCorrespondence { 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminSystemID", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminSystemPriority", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminKey", 
          "CIM_LAGPortPartnerSettings.PortPartnerAdminPort", 
          "CIM_LAGPortPartnerConnection.PortPartnerOperPortPriority" }]
   uint16 PortPartnerAdminPortPriority;


};
