// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSLSPInLSP
// ==================================================================
   [Association, Experimental, Aggregation, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "Defines the nesting relationship of LSPs within LSPs. "
       "Arbitrary hierarchies of LSPs are possible." )]
class CIM_MPLSLSPInLSP : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Description ( "The higher-level LSP containing another LSP." )]
   CIM_MPLSLSP REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( 
          "The LSP that is nested in the one referenced as GroupComponent."
           )]
   CIM_MPLSLSP REF PartComponent;


};
