// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="NetworksCR00043" type ="change">
// To the Experimental VLANCapabilities class:
//  1) Rename class to be VLANSystemCapabilities
//    2) Add Properties: MaxMTUsize, and MinMTUsize. </change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_VLANSystemCapabilities
// ==================================================================
   [Experimental, Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::Network::VLAN" ), 
    Description ( 
       "Properties in VLANSystemCapabilities represent the "
       "ComputerSystem\'s constraints and capabilities for VLANs. The "
       "information included in this class addresses the resource "
       "limits for the ComputerSystem." )]
class CIM_VLANSystemCapabilities : CIM_Capabilities {

      [Description ( "The maximum MTU size for the VLAN, in bytes." ), 
       Units ( "Bytes" ), 
       ModelCorrespondence { "CIM_NetworkVLAN.TransmissionSize", 
          "CIM_VLANSystemCapabilities.MinMTUsize" }, 
       PUnit ( "byte" )]
   uint16 MaxMTUsize;

      [Description ( "The minimum MTU size for the VLAN, in bytes." ), 
       Units ( "Bytes" ), 
       ModelCorrespondence { "CIM_NetworkVLAN.TransmissionSize", 
          "CIM_VLANSystemCapabilities.MaxMTUsize" }, 
       PUnit ( "byte" )]
   uint16 MinMTUsize;

      [Description ( 
          "The maximum number of IEEE 802.1Q VLANs that this device supports."
           ), 
       MappingStrings { 
          "MIB.IETF|Q-BRIDGE-MIB.dot11MaxSupportedVlans" }]
   uint16 MaxSupportedVLANs;

      [Description ( 
          "The maximum number of IEEE 802.1Q VLAN Ids that this "
          "device supports." ), 
       MappingStrings { "MIB.IETF|Q-BRIDGE-MIB.dot1qMaxVlanId" }]
   uint16 MaxVLANId;


};
