// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_GARPMembershipSettingData
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::VLAN" ), 
    Description ( 
       "Configuration for the Generic Attribute Registration Protocol "
       "(GARP). GARP is a protocol used by switches and end stations "
       "to register and de-register attribute values, such as VLAN "
       "Ids. The GVRP is an application of GARP for VLAN registration. "
       "The properties (timers) in this class are GARP control "
       "information about every ProtocolEndpoint supporting GARP & "
       "GVRP." )]
class CIM_GARPMembershipSettingData : CIM_ConnectivityMembershipSettingData {

      [Description ( "The GARP join time." ), 
       Units ( "MilliSeconds" ), 
       MappingStrings { "MIB.IETF|Q-BRIDGE-MIB.dot1dPortGarpJoinTime" }, 
       PUnit ( "second * 10^-3" )]
   uint32 Dot1dPortGarpJoinTime;

      [Description ( "The GARP leave time." ), 
       Units ( "MilliSeconds" ), 
       MappingStrings { 
          "MIB.IETF|Q-BRIDGE-MIB.dot1dPortGarpLeaveTime" }, 
       PUnit ( "second * 10^-3" )]
   uint32 Dot1dPortGarpLeaveTime;

      [Description ( "The GARP leave all time." ), 
       Units ( "MilliSeconds" ), 
       MappingStrings { 
          "MIB.IETF|Q-BRIDGE-MIB.dot1dPortGarpLeaveAllTime" }, 
       PUnit ( "second * 10^-3" )]
   uint32 Dot1dPortGarpLeaveAllTime;


};
