// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_FCIPSettings
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::ChannelExtender" ), 
    Description ( 
       "FCIPSettings class defines the attributes that affect the "
       "behavior of an Fibre Channel ProtocolEndpoint. The attributes "
       "are tied to the Fibre Channel ProtocolEndpoint though an "
       "ElementSettingData association. This class may also be used to "
       "specify the default settings for all Fibre Channel "
       "ProtocolEndpoint instances created on a ComputerSystem though "
       "an ElementSettingData association to the ComputerSystem. "
       "Processes that create new instances of Fibre Channel "
       "ProtocolEndpoint and the associated setting data should check "
       "for a FCIPSettings instance associated with the ComputerSystem "
       "and should only create a new instance of FCIPSettings specific "
       "to the Fibre Channel ProtocolEndpoint if the default settings "
       "need to be overridden for the specific Fibre Channel "
       "ProtocolEndpoint instance." )]
class CIM_FCIPSettings : CIM_SettingData {

      [Write, Description ( 
          "Identify the types of FCIP SOF values to be carried on "
          "the connection. (1) Class F (2) Class 2 (3) Class 3 (4) "
          "Class 4." ), 
       ValueMap { "1", "2", "3", "4" }, 
       Values { "SOF(F)", "SOF(2)", "SOF(3)", "SOF(4)" }, 
       MappingStrings { 
          "Fibre Channel Over TCP/IP (FCIP) Draft.IETF|Section 8.1" }]
   uint16 ConnectionUsageFlags;

      [Write, Description ( 
          "Timeout to wait for echoed FCIP Special Frame bytes." ), 
       Units ( "Seconds" ), 
       MinValue ( 90 ), 
       MappingStrings { 
          "Fibre Channel Over TCP/IP (FCIP) Draft.IETF|Section 8.1" }, 
       PUnit ( "second" )]
   uint32 SpecialFrameTimeout = 90;

      [Write, Description ( 
          "FC Keep Alive Timeout value to be applied to the new TCP "
          "Connection." ), 
       Units ( "Seconds" ), 
       MappingStrings { 
          "Fibre Channel Over TCP/IP (FCIP) Draft.IETF|Section 8.1" }, 
       PUnit ( "second" )]
   uint32 KeepAliveTimeout;


};
