// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSReverseDirectionTunnel
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "Tunnels are unidirectional. This association relates two TE "
       "tunnels that carry traffic in reverse directions, creating a "
       "bi-directional connection." )]
class CIM_MPLSReverseDirectionTunnel : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Max ( 1 ), 
       Description ( 
          "An MPLSTunnel, which operates in the reverse direction "
          "of the Dependent reference." )]
   CIM_MPLSTunnel REF Antecedent;

      [Override ( "Dependent" ), 
       Max ( 1 ), 
       Description ( 
          "An MPLSTunnel, which operates in the reverse direction "
          "of the Antecedent reference." )]
   CIM_MPLSTunnel REF Dependent;


};
