// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSProtocolEndpointStats
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "This class represents the statistics for an MPLSProtocol "
       "Endpoint. The statistics are associated with the Endpoint "
       "using the relationship CIM_ElementStatisticalData." )]
class CIM_MPLSProtocolEndpointStats : CIM_StatisticalData {

      [Description ( 
          "This object contains the number of top-most labels that "
          "are in use at this point in time on this interface in "
          "the incoming direction." ), 
       Gauge, MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInterfaceInLabelsUsed" }]
   uint32 InLabelsUsed;

      [Description ( 
          "This object contains the number of top-most labels that "
          "are in use at this point in time on this interface in "
          "the outgoing direction." ), 
       Gauge, MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInterfaceOutLabelsUsed" }]
   uint32 OutLabelsUsed;

      [Description ( 
          "This object counts the number of labeled packets that "
          "have been received on this interface and were discarded "
          "because there was no matching cross-connect entry." ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInterfaceFailedLabelLookup" }]
   uint32 FailedLabelLookups;

      [Description ( 
          "This object counts the number of outgoing MPLS packets "
          "that required fragmentation before transmission on this "
          "interface." ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-LSR-MIB.MPLSInterfaceOutFragments" }]
   uint32 NumberOfPacketsFragmented;


};
