// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR1529.001" type ="add">
// Add property iSCSINodeCreationSupported.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_iSCSIConfigurationCapabilities
// ==================================================================
   [Experimental, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Network::iSCSI" ), 
    Description ( 
       "A subclass of Capabilities that defines the capabilities of a "
       "iSCSIConfigurationService." )]
class CIM_iSCSIConfigurationCapabilities : CIM_Capabilities {

      [Description ( 
          "iSCSI Ports are modeled by instances of "
          "iSCSIProtocolEndpoints. If true, this property indicates "
          "that iSCSIProtocolEndpoints may be dynamically created "
          "and deleted in a Node. If false, iSCSIProtocolEndpoints "
          "are preexisting and statically defined within the Node." )]
   boolean iSCSIProtocolEndpointCreationSupported = false;

      [Description ( 
          "If false, the implementation chooses the Identifier for "
          "the iSCSIProtocolEndpoint and the Identifier cannot be "
          "supplied as a parameter to CreateiSCSIProtocolEndpoint "
          "and MUST be NULL." )]
   boolean IdentifierSelectionSupported = false;

      [Description ( 
          "iSCSI Nodes are modeled by instances of "
          "SCSIProtocolController. If true, this property indicates "
          "that iSCSI Nodes may be dynamically created and deleted "
          "in a NetworkEntity. If false, iSCSI Nodes are "
          "pre-existing and statically defined within the Entity." )]
   boolean iSCSINodeCreationSupported = false;


};
