// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_NATStaticSettings
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::NAT" ), 
    Description ( 
       "NATStaticSettings describes a single static address "
       "translation - both the local and global sides. It is a "
       "specialization of NATSettingData." )]
class CIM_NATStaticSettings : CIM_NATSettingData {

      [Description ( 
          "Specifies the \'inside\' address for translation. "
          "Whether the address is translated \'to\' or \'from\' is "
          "dependent on the value of the inherited property, "
          "IsInside. If IsInside is TRUE, then LocalAddress "
          "represents the address of a system on the \'inside\' "
          "network, that is translated to the GlobalAddress for "
          "external access. On the other hand, if IsInside is "
          "FALSE, then LocalAddress represents the address of an "
          "\'outside\' host as it appears to the \'inside\' "
          "network. In this case, the GlobalAddress is translated "
          "to the LocalAddress for \'inside\' network access." ), 
       ModelCorrespondence { "CIM_NATSettingData.IsInside" }]
   string InsideAddress;

      [Description ( 
          "Specifies the \'outside\' address for translation. "
          "Whether the address is translated \'to\' or \'from\' is "
          "dependent on the value of the inherited property, "
          "IsInside. If IsInside is TRUE, then GlobalAddress "
          "represents the address of an \'inside\' host, as it "
          "appears to the outside world. In this case, the "
          "LocalAddress is translated to the GlobalAddress for "
          "external access. On the other hand, if IsInside is "
          "FALSE, then GlobalAddress represents the address of an "
          "\'outside\' host as assigned on the outside network, by "
          "its owner. This address is translated to the "
          "LocalAddress for access through the \'inside\' network." ), 
       ModelCorrespondence { "CIM_NATSettingData.IsInside" }]
   string OutsideAddress;


};
