// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_LAGControlCapabilities
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::8023LAG" ), 
    Description ( 
       "This class establishes the control protocol support of the "
       "system. The Capabilities instance is associated to a network "
       "ComputerSystem via the ElementCapabilities relationship." )]
class CIM_LAGControlCapabilities : CIM_Capabilities {

      [Description ( 
          "A LAG may be under manual control (i.e., amanagement "
          "station is responsible for the additon and removal of "
          "LAG members) or automatic (i.e., a control protocol is "
          "employed to establish LAG membership." ), 
       ValueMap { "2", "3" }, 
       Values { "Manual", "Automatic" }]
   uint16 LAGControlMode = 2;

      [Description ( 
          "When the LAGMode is automatic, this propertyidentifies "
          "the control protocol in use." ), 
       ValueMap { "2", "3", "4..32767", ".." }, 
       Values { "None", "LACP", "DMTF Reserved", "Vendor Reserved" }]
   uint16 LAGControlProtocol;


};
