// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// <change cr="ArchCR00089.003" type="add">Add PUnit qualifier values
// to Units qualifier values.</change>
// ==================================================================
//  CIM_MPLSTunnelStats
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "This class represents the statistics for an MPLSTunnel. The "
       "statistics are associated to the tunnel using the "
       "relationship, CIM_ElementStatisticalData." )]
class CIM_MPLSTunnelStats : CIM_StatisticalData {

      [Description ( 
          "Specifies the total time the primary tunnel has been "
          "active. A primary tunnel is found/designated in "
          "situations where multiple tunnels exist - i.e., when "
          "parallel or backup tunnels are defined." ), 
       Units ( "Hundredths of a Second" ), 
       Counter, MaxValue ( 4294967295 ), 
       MappingStrings { 
          "MIB.IETF|MPLS-TE-MIB.MPLSTunnelPrimaryTimeUp" }, 
       PUnit ( "second * 10^-2" )]
   uint32 TunnelPrimaryTimeUp;

      [Description ( 
          "Specifies the number of times the paths have changed for "
          "this tunnel." ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-TE-MIB.MPLSTunnelPathChanges" }]
   uint32 TunnelPathChanges;

      [Description ( 
          "Specifies the time since the last path change for this tunnel."
           ), 
       Units ( "Hundredths of a Second" ), 
       Counter, MaxValue ( 4294967295 ), 
       MappingStrings { 
          "MIB.IETF|MPLS-TE-MIB.MPLSTunnelLastPathChange" }, 
       PUnit ( "second * 10^-2" )]
   uint32 TunnelLastPathChange;

      [Description ( 
          "Specifies the number of times the operational status of "
          "this tunnel has changed." ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-TE-MIB.MPLSTunnelStateTransitions" }]
   uint32 TunnelStateTransitions;

      [Description ( 
          "This value identifies the total time for which the the "
          "OperationalStatus of the tunnel is up (i.e., \"OK\"=2)." ), 
       Units ( "Hundredths of a Second" ), 
       Counter, MappingStrings { 
          "MIB.IETF|MPLS-TE-MIB.MPLSTunnelInstanceUpTime" }, 
       PUnit ( "second * 10^-2" )]
   uint32 TunnelInstanceUpTime;


};
