// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_MPLSBackupLSP
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::MPLS" ), 
    Description ( 
       "Identifies an LSP as a backup LSP for a traffic trunk." )]
class CIM_MPLSBackupLSP : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The backup LSP for the traffic trunk." )]
   CIM_MPLSLSP REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The traffic trunk using the LSP for backup." )]
   CIM_MPLSTunnel REF Dependent;

      [Description ( 
          "The preference for the use of the LSP, if more than one "
          "LSP is available to a trunk. Possible values are 0 to 7, "
          "with 7 indicating the highest preference." ), 
       MinValue ( 0 ), 
       MaxValue ( 7 )]
   uint16 Preference;


};
