// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_TimeoutsForNATTranslation
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Network::NAT" ), 
    Description ( 
       "TimeoutsForNATTranslation describes general setting and "
       "configuration data for the NAT translation service running on "
       "a system. The scoping system is described using the inherited "
       "ScopedSetting association." )]
class CIM_TimeoutsForNATTranslation : CIM_ScopedSettingData {

      [Description ( 
          "Specifies the idle timeout (as a datetime interval) for "
          "dynamic translations (ones involving an address pool). "
          "The default value is 86400 seconds." )]
   datetime TranslationTimeout = "00000000000000.086400:000";

      [Description ( 
          "Specifies the idle timeout (as a datetime interval) that "
          "applies to port address translations over a UDP Port. "
          "The default value is 300 seconds." )]
   datetime UDPTimeout = "00000000000000.000300:000";

      [Description ( 
          "Specifies the idle timeout (as a datetime interval) that "
          "applies to port address translations over a TCP Port. "
          "The default value is 86400 seconds." )]
   datetime TCPTimeout = "00000000000000.086400:000";


};
