// Copyright (c) 2006 DMTF.  All rights reserved.
// <change cr="WGAPPCR00043.007" type ="add">Add Discrete
// Metrics to CIM metrics model.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ===================================================================
// DiscreteMetricDefinitionDependency
// ===================================================================
   [Association, Experimental, Version ( "2.13.0" ), 
    UMLPackagePath ( "CIM::Metrics::BaseMetric" ), 
    Description ( 
       "Association between a BaseMetricDefinition instance "
       "representing an analog metric type, and any "
       "DiscreteMetricDefinition instances representing discrete "
       "metric types based upon this analog metric type. \n"
       "For a definition of the discrete metrics concept and how the "
       "existence of instances of this association class control the "
       "existence of the discrete metric values, refer to the "
       "description of DiscreteMetricDefinition." )]
class CIM_DiscreteMetricDefinitionDependency : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Min ( 1 ), 
       Max ( 1 )]
   CIM_BaseMetricDefinition REF Antecedent;

      [Override ( "Dependent" ), 
       Min ( 0 )]
   CIM_DiscreteMetricDefinition REF Dependent;


};
