// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ProviderLibrary 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "A ProviderLibrary consists of one or more Providers. It can be "
       "enabled/disabled - which affects the component Services." )]
class CIM_ProviderLibrary : CIM_EnabledLogicalElement {

      [Key, Override ( "Name" ), 
       Description ( 
          "A human-readable name that uniquely identifies the "
          "Provider Library. Name is chosen as one of the keys for "
          "correspondence with the keys/identity of the component "
          "Provider Services." )]
   string Name;

      [Required, Description ( 
          "An implementation specific string that identifies the "
          "handle of the provider." )]
   string Handle;


};
