// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ProviderInProviderLibrary 
// ==================================================================
   [Association, Experimental, Aggregation, Composition, Version ( 
       "2.8.1000" ), 
    UMLPackagePath ( "CIM::Interop" ), 
    Description ( 
       "An association describing the Providers that are contained in "
       "a ProviderLibrary." )]
class CIM_ProviderInProviderLibrary : CIM_Component {

      [Aggregate, Override ( "GroupComponent" ), 
       Max ( 1 ), 
       Description ( "The CIM ProviderLibrary." )]
   CIM_ProviderLibrary REF GroupComponent;

      [Override ( "PartComponent" ), 
       Description ( "The CIM Provider." )]
   CIM_Provider REF PartComponent;


};
