// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01503" type = "deprecate"> Deprecate
// AccountIdentity, SecurityServiceForSystem, ManagesAccountOnSystem,
// and ServiceUsesSecurityService </change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AccountIdentity
// ==================================================================
   [Association, Deprecated { "CIM_ConcreteIdentity" }, 
    Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::User::Account" ), 
    Description ( 
       "CIM_AccountIdentity relates a system Account with the Identity "
       "that is established. Since Account also carries Identity "
       "semantics, the LogicalIdentity association is defined as the "
       "superclass of this association. This association does not add "
       "any constraints or semantics to ConcreteIdentity. As a result, "
       "it is deprecated." )]
class CIM_AccountIdentity : CIM_LogicalIdentity {

      [Deprecated { "CIM_ConcreteIdentity.SystemElement" }, 
       Override ( "SystemElement" ), 
       Description ( "The Account that establishes Identity." )]
   CIM_Account REF SystemElement;

      [Deprecated { "CIM_ConcreteIdentity.SameElement" }, 
       Override ( "SameElement" ), 
       Description ( "The Identity established by the Account." )]
   CIM_Identity REF SameElement;


};
