// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01503" type = "deprecate"> Deprecate
// AccountIdentity, SecurityServiceForSystem, ManagesAccountOnSystem,
// and ServiceUsesSecurityService </change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_ServiceUsesSecurityService
// ==================================================================
   [Association, Deprecated { "CIM_ServiceServiceDependency" }, 
    Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( 
       "This relationship associates a Service with the Security "
       "Services that it uses. This association does not add any "
       "constraints or semantics to ServiceServiceDependency. As a "
       "result, it is deprecated." )]
class CIM_ServiceUsesSecurityService : CIM_ServiceServiceDependency {

      [Deprecated { "CIM_ServiceServiceDependency.Antecedent" }, 
       Override ( "Antecedent" )]
   CIM_SecurityService REF Antecedent;

      [Deprecated { "CIM_ServiceServiceDependency.Dependent" }, 
       Override ( "Dependent" )]
   CIM_Service REF Dependent;


};
