// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="CIMCoreCR00750" type = "change"> Clarification of CredentialContext </change>
// <change cr="DMTFCR01379" type = "new"> Add Credential Context
// </change>
// <change cr="DMTFCR01222" type = "new"> Define a CredentialContext
// association </change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_CredentialContext
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::User::Credential" ), 
    Description ( 
       "This relationship defines a context (e.g., a System or "
       "Service) of a Credential. One example is a shared secret/ "
       "password which is defined within the context of an application "
       "(or Service). Generally, there is one scoping element for a "
       "Credential, however the multiplicities of the association "
       "allow a Credential to be scoped by more than one element. If "
       "this association is not instantiated for a Credential, that "
       "Credential is assumed to be scoped to the Namespace.\n"
       "This association may also be used to indicate that a "
       "Credential is valid in some other environment. For instance "
       "associating the Credential to a RemoteServiceAccessPoint would "
       "indicate that the Credential is used to access the remote "
       "service." )]
class CIM_CredentialContext {

      [Key, Description ( "A Credential whose context is defined." )]
   CIM_Credential REF ElementInContext;

      [Key, Description ( 
          "The ManagedElement that provides context or scope for "
          "the Credential." )]
   CIM_ManagedElement REF ElementProvidingContext;


};
