// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01503" type = "deprecate"> Deprecate
// AccountIdentity, SecurityServiceForSystem, ManagesAccountOnSystem,
// and ServiceUsesSecurityService </change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SecurityServiceForSystem
// ==================================================================
   [Association, Deprecated { "CIM_ServiceAvailableToElement" }, 
    Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::User::SecurityServices" ), 
    Description ( 
       "The CIM_SecurityServiceForSystem provides the association "
       "between a System and a SecurityService that provides services "
       "for that system. This association does not add any constraints "
       "or semantics to ServiceAvailableToElement. As a result, it is "
       "deprecated." )]
class CIM_SecurityServiceForSystem : CIM_ProvidesServiceToElement {

      [Deprecated { "CIM_ServiceAvailableToElement.ServiceProvided" }, 
       Override ( "Antecedent" ), 
       Description ( 
          "The SecurityService that provides services for the system."
           )]
   CIM_SecurityService REF Antecedent;

      [Deprecated { "CIM_ServiceAvailableToElement.UserOfService" }, 
       Override ( "Dependent" ), 
       Description ( 
          "The system that is dependent on the security service." )]
   CIM_System REF Dependent;


};
