// Copyright (c) 2006 DMTF.  All rights reserved.
// <change cr="WIPCR00306.000" type="add">Enlarge the scope of the 
// relationship represented by the CIM_AssignedIdentity class.  Note 
// that this meant taking this class back to experimental in the
// experimental MOF.  </change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_AssignedIdentity 
// ==================================================================
   [Association, Version ( "2.14.0" ), 
    UMLPackagePath ( "CIM::User::Identity" ), 
    Description ( 
       "This relationship associates an Identity to a specific "
       "ManagedElement, whose trust and account information is "
       "represented." )]
class CIM_AssignedIdentity {

      [Key, Description ( 
          "An Identity of the referenced ManagedElement." )]
   CIM_Identity REF IdentityInfo;

      [Key, Description ( 
          "The ManagedElement assigned to or representing a "
          "specific Identity." )]
   CIM_ManagedElement REF ManagedElement;


};
