// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SWRManageableAspect 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Application::SWResources" ), 
    Description ( 
       "SWRManageableAspect is the association that allows to express "
       "the shared control between an software resource (as being the "
       "interval view of the software) and its corresponding external "
       "entity, e.g., a LogicalFile. It is possible to express that "
       "several systems (that run software) and one external, "
       "incompassing system (in general the OS) exercise control." )]
class CIM_SWRManageableAspect : CIM_LogicalIdentity {

      [Override ( "SameElement" ), 
       Description ( 
          "This reference points to the software resource that is "
          "aspect in the relationship." )]
   CIM_SoftwareResource REF SameElement;

      [Override ( "SystemElement" ), 
       Max ( 1 ), 
       Description ( 
          "This reference points to the entity viewed and "
          "controlled by the external, encompassing system like the "
          "OS. It is not the aspect." )]
   CIM_ManagedElement REF SystemElement;


};
