// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SWRPEP 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Application::SWResources" ), 
    Description ( 
       "This protocol endpoint is an software resource of software "
       "(e.g., an application system). It may be the internal view of "
       "an external ProtocolEndpoint which is controlled entirely or "
       "partially by the software." )]
class CIM_SWRPEP : CIM_SoftwareResource {

      [Override ( "IsAspect" ), 
       Description ( 
          "The default is that it is an aspect (value 2)." )]
   uint16 IsAspect = 2;

      [Override ( "ByReference" ), 
       Description ( 
          "The default is that item references are in the PEP (value 2)."
           )]
   uint16 ByReference = 2;

      [Override ( "SoftwareResourceType" ), 
       Description ( 
          "The default is of course \'Protocol Endpoint\' (value 3)." )]
   uint16 SoftwareResourceType = 3;


};
