// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SWRPEPAspect 
// ==================================================================
   [Association, Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Application::SWResources" ), 
    Description ( 
       "SWRPEPAspect is the association between multiple communication "
       "endpoint software resources (i.e., the aspects) and the one "
       "endpoint controlled by the operating system or middleware "
       "outside the software." )]
class CIM_SWRPEPAspect : CIM_SWRManageableAspect {

      [Override ( "SystemElement" ), 
       Description ( 
          "The protocol endpoint which is viewed as software resource."
           )]
   CIM_ProtocolEndpoint REF SystemElement;

      [Override ( "SameElement" ), 
       Description ( 
          "SameElement is the aspect: the software resource "
          "\'Protocol Endpoint\'." )]
   CIM_SWRPEP REF SameElement;


};
