// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_SWRDatabase 
// ==================================================================
   [Experimental, Version ( "2.8.1000" ), 
    UMLPackagePath ( "CIM::Application::SWResources" ), 
    Description ( 
       "This database is an software resource of software. It may be "
       "the internal view of an external CommonDatabase which is "
       "controlled entirely or partially by the software. \n"
       "SWRDatabase should not be confused with databases commonly "
       "provided by database systems and used by software (e.g., "
       "application systems). It describes databases that are "
       "implemented by the software." )]
class CIM_SWRDatabase : CIM_SoftwareResource {

      [Override ( "IsAspect" ), 
       Description ( 
          "The default is that it is an aspect (value 2)." )]
   uint16 IsAspect = 2;

      [Override ( "ByReference" ), 
       Description ( 
          "The default is that item copies are in the database (value 2)."
           )]
   uint16 ByReference = 2;

      [Override ( "SoftwareResourceType" ), 
       Description ( 
          "The default is of course \'Database\' (value 8)." )]
   uint16 SoftwareResourceType = 8;


};
